# Generated by bootc-assemble v0.1.0
# Manifest: bootc-assemble.yaml
# Fragments: epel (repos), postgresql (repos), tailscale (config), grafana (config), hashicorp (config), cis-hardening (config), node-exporter (config), nginx (config)
# Resolved digests:
#   base: registry.redhat.io/rhel10/rhel-bootc:10.0@sha256:d4a22b356b3ed54acb428a9d773f0e1bc3c67a7fd433b5bc245538eedbcbc349
#   epel: quay.io/marrusl2/fragments/epel:10@sha256:9f57b0f4ee38ade10fe0c9a6245c61c11992c9d6cf2fd72d41b05ac52727814f
#   postgresql: quay.io/marrusl2/fragments/postgresql:17@sha256:265b7c8a1a7847316c4041295ed98818de5620cb6ee2bf479b2995d67abadf20
#   tailscale: quay.io/marrusl2/fragments/tailscale:1.82.0@sha256:9537e3fe0f18dc046e095f2123a04923688dcbf50273f3ef2e42ccb13fa51709
#   grafana: quay.io/marrusl2/fragments/grafana:11.0@sha256:20e64a837ac681e2b0b63a9fb43dca66ff5688f643e34f4c18c84b957f75e4ad
#   hashicorp: quay.io/marrusl2/fragments/hashicorp:1.0@sha256:54704c67eed28c3d629f733da0f006ebab48bd975acbeac69e45feafcb39b4a8
#   cis-hardening: quay.io/marrusl2/fragments/cis-hardening:2.1@sha256:12afd31a69e011572c95e08f17b612836665e07da4ab5133299e76d82db3c054
#   node-exporter: quay.io/marrusl2/fragments/node-exporter:1.8.0@sha256:1fd19ad81b0837dede6f413107c05488bff9d51be48d402a50e111d5d46c1a49
#   nginx: quay.io/marrusl2/fragments/nginx:1.26@sha256:c6d2842fe853029868101681eba305924ad79cab0a144fdffffb90cf1fcf5e54
# Override summary: no file path collisions detected

# --- Fragment stages ---
FROM quay.io/marrusl2/fragments/epel@sha256:9f57b0f4ee38ade10fe0c9a6245c61c11992c9d6cf2fd72d41b05ac52727814f AS frag-epel  # :10
FROM quay.io/marrusl2/fragments/postgresql@sha256:265b7c8a1a7847316c4041295ed98818de5620cb6ee2bf479b2995d67abadf20 AS frag-postgresql  # :17
FROM quay.io/marrusl2/fragments/tailscale@sha256:9537e3fe0f18dc046e095f2123a04923688dcbf50273f3ef2e42ccb13fa51709 AS frag-tailscale  # :1.82.0
FROM quay.io/marrusl2/fragments/grafana@sha256:20e64a837ac681e2b0b63a9fb43dca66ff5688f643e34f4c18c84b957f75e4ad AS frag-grafana  # :11.0
FROM quay.io/marrusl2/fragments/hashicorp@sha256:54704c67eed28c3d629f733da0f006ebab48bd975acbeac69e45feafcb39b4a8 AS frag-hashicorp  # :1.0
FROM quay.io/marrusl2/fragments/cis-hardening@sha256:12afd31a69e011572c95e08f17b612836665e07da4ab5133299e76d82db3c054 AS frag-cis-hardening  # :2.1
FROM quay.io/marrusl2/fragments/node-exporter@sha256:1fd19ad81b0837dede6f413107c05488bff9d51be48d402a50e111d5d46c1a49 AS frag-node-exporter  # :1.8.0
FROM quay.io/marrusl2/fragments/nginx@sha256:c6d2842fe853029868101681eba305924ad79cab0a144fdffffb90cf1fcf5e54 AS frag-nginx  # :1.26

# --- Base ---
FROM registry.redhat.io/rhel10/rhel-bootc@sha256:d4a22b356b3ed54acb428a9d773f0e1bc3c67a7fd433b5bc245538eedbcbc349  # :10.0

# --- Phase: packages (20) ---
RUN dnf install -y \
        htop \
        tmux \
        jq \
        tailscale \
        grafana \
        postgresql17-server \
        vault \
        golang-github-prometheus-node-exporter \
        nginx \
    && dnf clean all

# --- Phase: preset-apply (35) ---
RUN systemctl preset-all --preset-mode=enable-only 2>/dev/null || true

# --- Phase: validation (90) ---
RUN bootc container lint
