use assert_cmd::Command;
use predicates::prelude::*;

#[test]
fn no_args_shows_help_or_requires_manifest() {
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.assert().failure();
}

#[test]
fn inspect_local_directory() {
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["inspect", "examples/fragments/epel"])
        .assert()
        .success()
        .stdout(predicate::str::contains("epel"))
        .stdout(predicate::str::contains("repos"))
        .stdout(predicate::str::contains("yum.repos.d"));
}

#[test]
fn inspect_tailscale_shows_hook() {
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["inspect", "examples/fragments/tailscale"])
        .assert()
        .success()
        .stdout(predicate::str::contains("entrypoint"));
}

#[test]
fn self_contained_conflicts_with_ocp() {
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["--self-contained", "out", "--ocp"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("cannot be used with"));
}

#[test]
fn self_contained_conflicts_with_output() {
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["--self-contained", "out", "--output", "Containerfile"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("cannot be used with"));
}

#[test]
fn self_contained_alone_does_not_conflict_with_outputs_default() {
    // --output has a default value, but relying on that default (never
    // passing --output explicitly) must not trip conflicts_with: only an
    // explicit --output alongside --self-contained is an error. This run
    // fails for an unrelated reason (no manifest file in the test's cwd),
    // which is exactly the point: it must not fail on an --output conflict.
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["--self-contained", "out"])
        .assert()
        .failure()
        .stderr(
            predicate::str::contains("reading manifest")
                .or(predicate::str::contains("was not generated by this tool")),
        );
}

#[test]
fn self_contained_refuses_existing_foreign_directory() {
    let tmp = tempfile::tempdir().unwrap();
    let dir = tmp.path().join("out");
    std::fs::create_dir(&dir).unwrap();
    std::fs::write(dir.join("README.md"), "not ours").unwrap();

    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["--self-contained", dir.to_str().unwrap()])
        .assert()
        .failure()
        .stderr(predicate::str::contains("was not generated by this tool"));
}
