use assert_cmd::Command;
use predicates::prelude::*;

#[test]
fn no_args_shows_help_or_requires_manifest() {
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.assert().failure();
}

#[test]
fn inspect_local_directory() {
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["inspect", "examples/fragments/epel"])
        .assert()
        .success()
        .stdout(predicate::str::contains("epel"))
        .stdout(predicate::str::contains("repos"))
        .stdout(predicate::str::contains("yum.repos.d"));
}

#[test]
fn inspect_without_mounts_prints_no_mount_section() {
    // Every shipped example fragment is mountless, so the section must be
    // absent rather than rendered empty.
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["inspect", "examples/fragments/epel"])
        .assert()
        .success()
        .stdout(predicate::str::contains("mount/").not());
}

#[test]
fn inspect_tailscale_shows_hook() {
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["inspect", "examples/fragments/tailscale"])
        .assert()
        .success()
        .stdout(predicate::str::contains("entrypoint"));
}

#[test]
fn inspect_grafana_shows_declarative_account_and_state() {
    // The grafana fragment declares its service account and state
    // directories as sysusers.d/tmpfiles.d tree content rather than
    // relying on the RPM's %post. Inspect must list both files, and
    // succeeding at all means the fragment satisfies the hooks
    // entrypoint contract.
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["inspect", "examples/fragments/grafana"])
        .assert()
        .success()
        .stdout(predicate::str::contains("usr/lib/sysusers.d/grafana.conf"))
        .stdout(predicate::str::contains("usr/lib/tmpfiles.d/grafana.conf"))
        .stdout(predicate::str::contains("entrypoint"));
}

#[test]
fn self_contained_conflicts_with_ocp() {
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["--self-contained", "out", "--ocp"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("cannot be used with"));
}

#[test]
fn self_contained_conflicts_with_output() {
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["--self-contained", "out", "--output", "Containerfile"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("cannot be used with"));
}

#[test]
fn self_contained_alone_does_not_conflict_with_outputs_default() {
    // --output has a default value, but relying on that default (never
    // passing --output explicitly) must not trip conflicts_with: only an
    // explicit --output alongside --self-contained is an error. This run
    // fails for an unrelated reason (no manifest file in the test's cwd),
    // which is exactly the point: it must not fail on an --output conflict.
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["--self-contained", "out"])
        .assert()
        .failure()
        .stderr(
            predicate::str::contains("reading manifest")
                .or(predicate::str::contains("was not generated by this tool")),
        );
}

#[test]
fn self_contained_refuses_existing_foreign_directory() {
    let tmp = tempfile::tempdir().unwrap();
    let dir = tmp.path().join("out");
    std::fs::create_dir(&dir).unwrap();
    std::fs::write(dir.join("README.md"), "not ours").unwrap();

    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["--self-contained", dir.to_str().unwrap()])
        .assert()
        .failure()
        .stderr(predicate::str::contains("was not generated by this tool"));
}

#[test]
fn materialize_mounts_requires_self_contained() {
    // The flag only means anything for the output mode that has to copy
    // mount material onto disk, so passing it alone must not be accepted
    // and then silently ignored.
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["--materialize-mounts"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("--self-contained"));
}

#[test]
fn materialize_mounts_is_accepted_alongside_self_contained() {
    // Fails for an unrelated reason (no manifest in the test's cwd), which
    // is the point: it must not fail on argument parsing.
    let mut cmd = Command::cargo_bin("osfragment-assemble").unwrap();
    cmd.args(["--self-contained", "out", "--materialize-mounts"])
        .assert()
        .failure()
        .stderr(
            predicate::str::contains("reading manifest")
                .or(predicate::str::contains("was not generated by this tool")),
        );
}
