apiVersion: bootc.io/v1alpha1
kind: Composition

base: quay.io/centos-bootc/centos-bootc:stream10

fragments:
  - image: quay.io/marrusl2/fragments/epel:10
    packages: [htop, tmux, jq]
  - image: quay.io/marrusl2/fragments/tailscale:1.82.0
  - image: quay.io/marrusl2/fragments/grafana:11.0
  - image: quay.io/marrusl2/fragments/postgresql:17
  - image: quay.io/marrusl2/fragments/hashicorp:1.0
    packages: [vault]
  - image: quay.io/marrusl2/fragments/cis-hardening:2.1
  - image: quay.io/marrusl2/fragments/node-exporter:1.8.0
  - image: quay.io/marrusl2/fragments/nginx:1.26
