apiVersion: bootc.io/v1alpha1
kind: Composition

base: registry.redhat.io/rhel10/rhel-bootc:10.0

fragments:
  - image: quay.io/mrussell/fragments/epel:10
    packages: [htop, tmux, jq]
  - image: quay.io/mrussell/fragments/tailscale:1.82.0
    packages: [tailscale]
  - image: quay.io/mrussell/fragments/grafana:11.0
    packages: [grafana]
  - image: quay.io/mrussell/fragments/postgresql:17
    packages: [postgresql17-server]
  - image: quay.io/mrussell/fragments/hashicorp:1.0
    packages: [vault]
  - image: quay.io/mrussell/fragments/cis-hardening:2.1
  - image: quay.io/mrussell/fragments/node-exporter:1.8.0
    packages: [golang-github-prometheus-node-exporter]
  - image: quay.io/mrussell/fragments/nginx:1.26
    packages: [nginx]
