apiVersion: bootc.io/v1alpha1
kind: Composition

base: quay.io/centos-bootc/centos-bootc:stream10

fragments:
  - image: quay.io/marrusl2/fragments/epel:10
    packages: [htop, tmux]
  - image: quay.io/marrusl2/fragments/cis-hardening:2.1
