apiVersion: bootc.io/v1alpha1
kind: Composition

base: registry.redhat.io/rhel10/rhel-bootc:10.0

fragments:
  - image: quay.io/marrusl2/fragments/grafana:11.0
    packages: [grafana]
    mirror: https://rpm-mirror.internal.corp/grafana/
  - image: quay.io/marrusl2/fragments/tailscale:1.82.0
    packages: [tailscale]
    mirror: https://rpm-mirror.internal.corp/tailscale/
