apiVersion: bootc.io/v1alpha1
kind: Composition

base: quay.io/centos-bootc/centos-bootc:stream10

fragments:
  - image: quay.io/marrusl2/fragments/grafana:11.0
    mirror: https://rpm-mirror.internal.corp/grafana/
  - image: quay.io/marrusl2/fragments/tailscale:1.82.0
    mirror: https://rpm-mirror.internal.corp/tailscale/
