.PHONY: srpm

NAME     := osfragment-assemble
SPECFILE := packaging/$(NAME).spec
VERSION  := $(shell sed -n 's/^Version:[[:space:]]*//p' $(SPECFILE))
TARBALL  := $(NAME)-$(VERSION).tar.gz
RPMBUILD := $(HOME)/rpmbuild

srpm:
	dnf install -y git rpm-build cargo rust
	mkdir -p $(RPMBUILD)/SOURCES $(RPMBUILD)/SPECS $(RPMBUILD)/SRPMS

	$(eval STAGING := $(shell mktemp -d))
	git archive --format=tar.gz --prefix=$(NAME)-$(VERSION)/ HEAD \
	    | tar -xz -C $(STAGING)

	cd $(STAGING)/$(NAME)-$(VERSION) && \
	    cargo vendor && \
	    mkdir -p .cargo && \
	    printf '[source.crates-io]\nreplace-with = "vendored-sources"\n\n[source.vendored-sources]\ndirectory = "vendor"\n' \
	        > .cargo/config.toml

	tar -czf $(RPMBUILD)/SOURCES/$(TARBALL) \
	    -C $(STAGING) $(NAME)-$(VERSION)
	rm -rf $(STAGING)

	cp $(SPECFILE) $(RPMBUILD)/SPECS/$(NAME).spec
	rpmbuild -bs --define "_topdir $(RPMBUILD)" $(RPMBUILD)/SPECS/$(NAME).spec
	cp $(RPMBUILD)/SRPMS/*.src.rpm $(outdir)/
