[fragment]
name = "postgresql"
version = "17"
description = "PostgreSQL Global Development Group RPM repository"
vendor = "PostgreSQL Global Development Group"

[fragment.provides]
repos = ["pgdg-common", "pgdg17"]

[fragment.packages]
required = [
    "postgresql17-server",
    "postgresql17",
]
