use anyhow::Result;
use std::fmt::Write;

use crate::fragment::is_repo_path;
use crate::loader::LoadedFragment;
use crate::manifest::{FragmentSource, Manifest};
use crate::validate::DeduplicationResult;

/// Split a container image reference into (name, optional_tag).
///
/// The tag separator is the last `:` that appears after the last `/`.
/// This correctly handles registry ports (e.g., `localhost:5000/image:tag`).
/// Returns `(full_ref, None)` when no tag is present or the ref already
/// contains a digest (`@`).
pub fn split_image_ref(image_ref: &str) -> (&str, Option<&str>) {
    // Digests are not tags — leave them alone
    if image_ref.contains('@') {
        return (image_ref, None);
    }

    let colon_search_start = image_ref.rfind('/').map(|p| p + 1).unwrap_or(0);

    match image_ref[colon_search_start..].find(':') {
        Some(offset) => {
            let colon_pos = colon_search_start + offset;
            (&image_ref[..colon_pos], Some(&image_ref[colon_pos + 1..]))
        }
        None => (image_ref, None),
    }
}

/// Returns the `--from=` argument for COPY instructions.
/// Uses inline image refs when stages are unnamed, named stage aliases otherwise.
fn copy_from_source(loaded: &LoadedFragment, use_named_stages: bool) -> String {
    if use_named_stages {
        format!("frag-{}", loaded.fragment.name)
    } else {
        let FragmentSource::Registry { ref image_ref } = loaded.source;
        image_ref.clone()
    }
}

pub fn generate_containerfile(
    manifest: &Manifest,
    fragments: &[LoadedFragment],
    base_digest: Option<&str>,
    _dedup: &DeduplicationResult,
    ocp: bool,
) -> Result<String> {
    let mut out = String::new();
    let use_named_stages = fragments.iter().any(|f| f.resolved_digest.is_some());

    // Header (standalone only — OCP omits to stay under MachineOSConfig limits)
    if !ocp {
        writeln!(out, "# Generated by osfragment-assemble v0.1.0")?;
        writeln!(out, "# Manifest: osfragment-assemble.yaml")?;

        let frag_summary: Vec<String> = fragments
            .iter()
            .map(|f| {
                format!(
                    "{} ({})",
                    f.fragment.name,
                    match f.fragment.phase {
                        crate::fragment::FragmentPhase::Repos => "repos",
                        crate::fragment::FragmentPhase::Config => "config",
                    }
                )
            })
            .collect();
        writeln!(out, "# Fragments: {}", frag_summary.join(", "))?;

        // Resolved digests (only when --pin-digests is used)
        let has_digests =
            base_digest.is_some() || fragments.iter().any(|f| f.resolved_digest.is_some());
        if has_digests {
            writeln!(out, "# Resolved digests:")?;
            if let Some(d) = base_digest {
                writeln!(out, "#   base: {}@{}", manifest.base, d)?;
            }
            for loaded in fragments {
                let mf = &manifest.fragments[loaded.manifest_index];
                if let Some(d) = &loaded.resolved_digest {
                    writeln!(out, "#   {}: {}@{}", loaded.fragment.name, mf.image, d)?;
                }
            }
        }

        // Compute override summary — detect file path collisions
        let mut path_owners: std::collections::HashMap<String, Vec<String>> =
            std::collections::HashMap::new();
        for loaded in fragments {
            for p in &loaded.tree_paths {
                if p.to_string_lossy().starts_with("tree/") {
                    let dest = p
                        .strip_prefix("tree")
                        .unwrap_or(p)
                        .to_string_lossy()
                        .to_string();
                    path_owners
                        .entry(dest)
                        .or_default()
                        .push(loaded.fragment.name.clone());
                }
            }
        }
        let collisions: Vec<_> = path_owners
            .iter()
            .filter(|(_, owners)| owners.len() > 1)
            .collect();
        if collisions.is_empty() {
            writeln!(out, "# Override summary: no file path collisions detected")?;
        } else {
            writeln!(
                out,
                "# Override summary: {} file path collision(s) detected",
                collisions.len()
            )?;
            for (path, owners) in &collisions {
                writeln!(
                    out,
                    "#   {} — written by: {} (last wins)",
                    path,
                    owners.join(", ")
                )?;
            }
        }
        writeln!(out)?;
    }

    // Fragment FROM stages (only when pinning digests — named stages for readability)
    if use_named_stages {
        if !ocp {
            writeln!(out, "# --- Fragment stages ---")?;
        }
        for loaded in fragments {
            let FragmentSource::Registry { ref image_ref } = loaded.source;
            writeln!(out, "FROM {} AS frag-{}", image_ref, loaded.fragment.name)?;
        }
        if !ocp {
            writeln!(out)?;
        }
    }

    // Main stage
    if ocp {
        writeln!(out, "FROM configs AS final")?;
    } else {
        writeln!(out, "# --- Base ---")?;
        let base_ref = if let Some(d) = base_digest {
            let (base_name, _tag) = split_image_ref(&manifest.base);
            format!("{}@{}", base_name, d)
        } else {
            manifest.base.clone()
        };
        writeln!(out, "FROM {}", base_ref)?;
    }
    if !ocp {
        writeln!(out)?;
    }

    // Repo files — must land before dnf install
    let has_repo_content = fragments
        .iter()
        .any(|f| f.tree_paths.iter().any(|p| is_repo_path(p)));
    if has_repo_content {
        if !ocp {
            writeln!(out, "# --- Repo files ---")?;
        }
        for loaded in fragments {
            let has_repo = loaded.tree_paths.iter().any(|p| is_repo_path(p));
            if !has_repo {
                continue;
            }
            let source = copy_from_source(loaded, use_named_stages);
            if loaded
                .tree_paths
                .iter()
                .any(|p| p.to_string_lossy().contains("yum.repos.d"))
            {
                writeln!(
                    out,
                    "COPY --from={} /fragment/tree/etc/yum.repos.d/ /etc/yum.repos.d/",
                    source
                )?;
            }
            if loaded
                .tree_paths
                .iter()
                .any(|p| p.to_string_lossy().contains("rpm-gpg"))
            {
                writeln!(
                    out,
                    "COPY --from={} /fragment/tree/etc/pki/rpm-gpg/ /etc/pki/rpm-gpg/",
                    source
                )?;
            }
        }

        // Mirror rewrites (must follow the repo COPYs)
        for loaded in fragments {
            let mf = &manifest.fragments[loaded.manifest_index];
            if let Some(mirror_url) = &mf.mirror {
                let repo_files: Vec<_> = loaded
                    .tree_paths
                    .iter()
                    .filter(|p| p.to_string_lossy().contains("yum.repos.d"))
                    .filter_map(|p| {
                        p.file_name()
                            .map(|f| format!("/etc/yum.repos.d/{}", f.to_string_lossy()))
                    })
                    .collect();
                for repo_file in &repo_files {
                    writeln!(
                        out,
                        "RUN sed -i 's|^baseurl=.*|baseurl={}|; s|^metalink=|#metalink=|; s|^mirrorlist=|#mirrorlist=|' {}",
                        mirror_url, repo_file
                    )?;
                }
            }
        }
        if !ocp {
            writeln!(out)?;
        }
    }

    // Packages
    let mut seen = std::collections::HashSet::new();
    let all_packages: Vec<String> = manifest
        .fragments
        .iter()
        .flat_map(|f| f.packages.iter().cloned())
        .filter(|p| seen.insert(p.clone()))
        .collect();
    if !all_packages.is_empty() {
        if !ocp {
            writeln!(out, "# --- Packages ---")?;
        }
        writeln!(out, "RUN dnf install -y \\")?;
        for pkg in &all_packages {
            writeln!(out, "        {} \\", pkg)?;
        }
        writeln!(out, "    && dnf clean all \\")?;
        writeln!(
            out,
            "    && rm -rf /var/log/dnf* /var/log/hawkey.log /var/lib/dnf/history.sqlite*"
        )?;
        if !ocp {
            writeln!(out)?;
        }
    }

    // Config files — after packages so fragment configs win over RPM defaults
    let has_config_content = fragments.iter().any(|f| {
        f.tree_paths
            .iter()
            .any(|p| p.to_string_lossy().starts_with("tree/") && !is_repo_path(p))
    });
    if has_config_content {
        if !ocp {
            writeln!(out, "# --- Config files ---")?;
        }
        for loaded in fragments {
            let has_non_repo = loaded
                .tree_paths
                .iter()
                .any(|p| p.to_string_lossy().starts_with("tree/") && !is_repo_path(p));
            if !has_non_repo {
                continue;
            }
            let source = copy_from_source(loaded, use_named_stages);
            writeln!(out, "COPY --from={} /fragment/tree/ /", source)?;
        }
        if !ocp {
            writeln!(out)?;
        }
    }

    // Hooks (must run after packages are installed)
    let hook_fragments: Vec<_> = fragments
        .iter()
        .filter(|f| !f.hook_paths.is_empty())
        .collect();
    if !hook_fragments.is_empty() {
        if !ocp {
            writeln!(out, "# --- Hooks ---")?;
        }
        for loaded in &hook_fragments {
            let source = copy_from_source(loaded, use_named_stages);
            let hooks_dir = format!("/tmp/frag-{}-hooks", loaded.fragment.name);
            writeln!(
                out,
                "COPY --from={} /fragment/hooks/ {}/",
                source, hooks_dir
            )?;

            // Build chained RUN command: hook1 && hook2 && ... && cleanup
            let mut run_cmd = String::from("RUN ");
            for (i, hook_path) in loaded.hook_paths.iter().enumerate() {
                if i > 0 {
                    run_cmd.push_str(" && ");
                }
                run_cmd.push_str(&format!("{}/{}", hooks_dir, hook_path.display()));
            }
            run_cmd.push_str(&format!(" && rm -rf {}", hooks_dir));
            writeln!(out, "{}", run_cmd)?;
        }
        if !ocp {
            writeln!(out)?;
        }
    }

    // Phase: preset-apply (35)
    if !ocp {
        writeln!(out, "# Apply systemd presets from fragments")?;
    }
    writeln!(
        out,
        "RUN systemctl preset-all --preset-mode=enable-only 2>/dev/null || true"
    )?;
    if !ocp {
        writeln!(out)?;
    }

    // Phase: validation (90)
    if !ocp {
        writeln!(out, "# --- Phase: validation (90) ---")?;
    }
    writeln!(out, "RUN bootc container lint")?;

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    use crate::fragment::{
        Fragment, FragmentConflicts, FragmentPackages, FragmentPhase, FragmentProvides,
    };
    use crate::loader::LoadedFragment;
    use crate::manifest::{FragmentSource, Manifest, ManifestFragment};

    fn make_repos_fragment(name: &str, digest: &str) -> (LoadedFragment, ManifestFragment) {
        let loaded = LoadedFragment {
            fragment: Fragment {
                name: name.to_string(),
                version: "10".into(),
                description: "test".into(),
                vendor: None,
                phase: FragmentPhase::Repos,
                provides: FragmentProvides {
                    repos: vec![name.to_string()],
                },
                packages: FragmentPackages { available: vec![] },
                conflicts: FragmentConflicts { fragments: vec![] },
            },
            tree_paths: vec![
                PathBuf::from("tree/etc/yum.repos.d/test.repo"),
                PathBuf::from("tree/etc/pki/rpm-gpg/RPM-GPG-KEY-test"),
            ],
            hook_paths: vec![],
            source: FragmentSource::Registry {
                image_ref: format!("quay.io/test/{}@sha256:{}", name, digest),
            },
            resolved_digest: Some(format!("sha256:{}", digest)),
            manifest_index: 0,
            repo_file_contents: std::collections::HashMap::new(),
        };
        let manifest_frag = ManifestFragment {
            image: format!("quay.io/test/{}:10", name),
            packages: vec!["htop".into()],
            mirror: None,
        };
        (loaded, manifest_frag)
    }

    fn make_config_fragment(name: &str, digest: &str) -> (LoadedFragment, ManifestFragment) {
        let loaded = LoadedFragment {
            fragment: Fragment {
                name: name.to_string(),
                version: "2.1".into(),
                description: "test".into(),
                vendor: None,
                phase: FragmentPhase::Config,
                provides: FragmentProvides { repos: vec![] },
                packages: FragmentPackages { available: vec![] },
                conflicts: FragmentConflicts { fragments: vec![] },
            },
            tree_paths: vec![PathBuf::from("tree/usr/lib/sysctl.d/99-hardening.conf")],
            hook_paths: vec![PathBuf::from("configure.sh")],
            source: FragmentSource::Registry {
                image_ref: format!("quay.io/test/{}@sha256:{}", name, digest),
            },
            resolved_digest: Some(format!("sha256:{}", digest)),
            manifest_index: 0,
            repo_file_contents: std::collections::HashMap::new(),
        };
        let manifest_frag = ManifestFragment {
            image: format!("quay.io/test/{}:2.1", name),
            packages: vec![],
            mirror: None,
        };
        (loaded, manifest_frag)
    }

    fn empty_dedup() -> crate::validate::DeduplicationResult {
        crate::validate::DeduplicationResult {
            deduplicated_repos: std::collections::HashMap::new(),
        }
    }

    #[test]
    fn generated_output_contains_digest_pinned_from() {
        let (epel, mf_epel) = make_repos_fragment("epel", "aaa111");
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output = generate_containerfile(
            &manifest,
            &[epel],
            Some("sha256:base123"),
            &empty_dedup(),
            false,
        )
        .unwrap();
        assert!(output.contains("@sha256:aaa111"));
        assert!(output.contains("@sha256:base123"));
        assert!(!output.contains("FROM quay.io/test/epel:10 AS"));
    }

    #[test]
    fn generated_output_has_section_ordering() {
        let (epel, mf_epel) = make_repos_fragment("epel", "aaa111");
        let (mut cis, mf_cis) = make_config_fragment("cis", "bbb222");
        cis.manifest_index = 1;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel, mf_cis],
        };
        let output = generate_containerfile(
            &manifest,
            &[epel, cis],
            Some("sha256:base123"),
            &empty_dedup(),
            false,
        )
        .unwrap();
        let repo_pos = output.find("Repo files").unwrap();
        let packages_pos = output.find("Packages").unwrap();
        let config_pos = output.find("Config files").unwrap();
        let hooks_pos = output.find("Hooks").unwrap();
        let preset_pos = output.find("preset-all").unwrap();
        let validation_pos = output.find("validation").unwrap();
        assert!(repo_pos < packages_pos);
        assert!(packages_pos < config_pos);
        assert!(config_pos < hooks_pos);
        assert!(hooks_pos < preset_pos);
        assert!(preset_pos < validation_pos);
    }

    #[test]
    fn generated_output_batches_packages() {
        let (epel, mf_epel) = make_repos_fragment("epel", "aaa111");
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output = generate_containerfile(
            &manifest,
            &[epel],
            Some("sha256:base123"),
            &empty_dedup(),
            false,
        )
        .unwrap();
        assert!(output.contains("dnf install -y"));
        assert!(output.contains("htop"));
    }

    #[test]
    fn generated_output_has_preset_apply() {
        let (mut cis, mf_cis) = make_config_fragment("cis", "bbb222");
        cis.manifest_index = 0;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_cis],
        };
        let output = generate_containerfile(
            &manifest,
            &[cis],
            Some("sha256:base123"),
            &empty_dedup(),
            false,
        )
        .unwrap();
        assert!(output.contains("systemctl preset-all --preset-mode=enable-only"));
    }

    #[test]
    fn generated_output_has_bootc_lint() {
        let (mut cis, mf_cis) = make_config_fragment("cis", "bbb222");
        cis.manifest_index = 0;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_cis],
        };
        let output = generate_containerfile(
            &manifest,
            &[cis],
            Some("sha256:base123"),
            &empty_dedup(),
            false,
        )
        .unwrap();
        assert!(output.contains("bootc container lint"));
    }

    #[test]
    fn no_packages_phase_when_no_packages() {
        let (mut cis, mf_cis) = make_config_fragment("cis", "bbb222");
        cis.manifest_index = 0;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_cis],
        };
        let output = generate_containerfile(
            &manifest,
            &[cis],
            Some("sha256:base123"),
            &empty_dedup(),
            false,
        )
        .unwrap();
        assert!(!output.contains("dnf install"));
    }

    #[test]
    fn mirror_generates_sed_rewrite() {
        let (epel, mut mf_epel) = make_repos_fragment("epel", "aaa111");
        mf_epel.mirror = Some("https://mirror.corp/epel/".into());
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output = generate_containerfile(
            &manifest,
            &[epel],
            Some("sha256:base123"),
            &empty_dedup(),
            false,
        )
        .unwrap();
        assert!(output.contains("sed"));
        assert!(output.contains("https://mirror.corp/epel/"));
    }

    #[test]
    fn repo_dedup_skips_non_canonical_provider() {
        let (epel, mf_epel) = make_repos_fragment("epel", "aaa111");
        let (mut node_exp, mf_node) = make_repos_fragment("node-exporter", "ccc333");
        node_exp.manifest_index = 1;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel, mf_node],
        };
        let mut dedup = empty_dedup();
        dedup
            .deduplicated_repos
            .insert("epel".to_string(), "epel".to_string());
        dedup
            .deduplicated_repos
            .insert("node-exporter".to_string(), "node-exporter".to_string());
        let output = generate_containerfile(
            &manifest,
            &[epel, node_exp],
            Some("sha256:base123"),
            &dedup,
            false,
        )
        .unwrap();
        // epel is canonical for its own repo — its COPY should appear
        let epel_copy_count = output.matches("COPY --from=frag-epel").count();
        assert!(epel_copy_count > 0);
    }

    #[test]
    fn split_image_ref_standard_registry() {
        let (name, tag) = super::split_image_ref("registry.redhat.io/rhel9/rhel-bootc:9.4");
        assert_eq!(name, "registry.redhat.io/rhel9/rhel-bootc");
        assert_eq!(tag, Some("9.4"));
    }

    #[test]
    fn split_image_ref_with_port() {
        let (name, tag) = super::split_image_ref("localhost:5000/myimage:latest");
        assert_eq!(name, "localhost:5000/myimage");
        assert_eq!(tag, Some("latest"));
    }

    #[test]
    fn split_image_ref_quay_with_tag() {
        let (name, tag) = super::split_image_ref("quay.io/centos-bootc/centos-bootc:stream9");
        assert_eq!(name, "quay.io/centos-bootc/centos-bootc");
        assert_eq!(tag, Some("stream9"));
    }

    #[test]
    fn split_image_ref_no_tag() {
        let (name, tag) = super::split_image_ref("registry.redhat.io/rhel9/rhel-bootc");
        assert_eq!(name, "registry.redhat.io/rhel9/rhel-bootc");
        assert_eq!(tag, None);
    }

    #[test]
    fn split_image_ref_with_digest() {
        let (name, tag) = super::split_image_ref("quay.io/image@sha256:abc123");
        assert_eq!(name, "quay.io/image@sha256:abc123");
        assert_eq!(tag, None);
    }

    #[test]
    fn split_image_ref_port_no_tag() {
        let (name, tag) = super::split_image_ref("localhost:5000/myimage");
        assert_eq!(name, "localhost:5000/myimage");
        assert_eq!(tag, None);
    }

    #[test]
    fn split_image_ref_simple_with_tag() {
        let (name, tag) = super::split_image_ref("nginx:latest");
        assert_eq!(name, "nginx");
        assert_eq!(tag, Some("latest"));
    }

    #[test]
    fn split_image_ref_simple_no_tag() {
        let (name, tag) = super::split_image_ref("nginx");
        assert_eq!(name, "nginx");
        assert_eq!(tag, None);
    }

    #[test]
    fn base_image_with_port_generates_correct_from() {
        let (epel, mf_epel) = make_repos_fragment("epel", "aaa111");
        let manifest = Manifest {
            base: "localhost:5000/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output = generate_containerfile(
            &manifest,
            &[epel],
            Some("sha256:base123"),
            &empty_dedup(),
            false,
        )
        .unwrap();
        // Must preserve the port in the pinned ref
        assert!(output.contains("FROM localhost:5000/rhel-bootc@sha256:base123"));
    }

    // --- Helpers for unpinned fragments ---

    fn make_unpinned_repos_fragment(name: &str) -> (LoadedFragment, ManifestFragment) {
        let loaded = LoadedFragment {
            fragment: Fragment {
                name: name.to_string(),
                version: "10".into(),
                description: "test".into(),
                vendor: None,
                phase: FragmentPhase::Repos,
                provides: FragmentProvides {
                    repos: vec![name.to_string()],
                },
                packages: FragmentPackages { available: vec![] },
                conflicts: FragmentConflicts { fragments: vec![] },
            },
            tree_paths: vec![
                PathBuf::from("tree/etc/yum.repos.d/test.repo"),
                PathBuf::from("tree/etc/pki/rpm-gpg/RPM-GPG-KEY-test"),
            ],
            hook_paths: vec![],
            source: FragmentSource::Registry {
                image_ref: format!("quay.io/test/{}:10", name),
            },
            resolved_digest: None,
            manifest_index: 0,
            repo_file_contents: std::collections::HashMap::new(),
        };
        let manifest_frag = ManifestFragment {
            image: format!("quay.io/test/{}:10", name),
            packages: vec!["htop".into()],
            mirror: None,
        };
        (loaded, manifest_frag)
    }

    fn make_unpinned_config_fragment(name: &str) -> (LoadedFragment, ManifestFragment) {
        let loaded = LoadedFragment {
            fragment: Fragment {
                name: name.to_string(),
                version: "2.1".into(),
                description: "test".into(),
                vendor: None,
                phase: FragmentPhase::Config,
                provides: FragmentProvides { repos: vec![] },
                packages: FragmentPackages { available: vec![] },
                conflicts: FragmentConflicts { fragments: vec![] },
            },
            tree_paths: vec![PathBuf::from("tree/usr/lib/sysctl.d/99-hardening.conf")],
            hook_paths: vec![PathBuf::from("configure.sh")],
            source: FragmentSource::Registry {
                image_ref: format!("quay.io/test/{}:2.1", name),
            },
            resolved_digest: None,
            manifest_index: 0,
            repo_file_contents: std::collections::HashMap::new(),
        };
        let manifest_frag = ManifestFragment {
            image: format!("quay.io/test/{}:2.1", name),
            packages: vec![],
            mirror: None,
        };
        (loaded, manifest_frag)
    }

    // --- Inline ref tests (unpinned mode) ---

    #[test]
    fn unpinned_uses_inline_copy_refs() {
        let (epel, mf_epel) = make_unpinned_repos_fragment("epel");
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output =
            generate_containerfile(&manifest, &[epel], None, &empty_dedup(), false).unwrap();
        // Inline image ref in COPY for repo files, no named FROM stage
        assert!(output.contains("COPY --from=quay.io/test/epel:10 /fragment/tree/etc/yum.repos.d/"));
        assert!(!output.contains("AS frag-epel"));
    }

    #[test]
    fn unpinned_uses_base_tag_not_digest() {
        let (epel, mf_epel) = make_unpinned_repos_fragment("epel");
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output =
            generate_containerfile(&manifest, &[epel], None, &empty_dedup(), false).unwrap();
        assert!(output.contains("FROM registry.redhat.io/rhel10/rhel-bootc:10.0"));
        assert!(!output.contains("@sha256:"));
    }

    #[test]
    fn unpinned_hooks_use_inline_copy_refs() {
        let (mut cis, mf_cis) = make_unpinned_config_fragment("cis");
        cis.manifest_index = 0;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_cis],
        };
        let output =
            generate_containerfile(&manifest, &[cis], None, &empty_dedup(), false).unwrap();
        assert!(output.contains(
            "COPY --from=quay.io/test/cis:2.1 /fragment/hooks/ /tmp/frag-cis-hooks/"
        ));
        assert!(output
            .contains("RUN /tmp/frag-cis-hooks/configure.sh && rm -rf /tmp/frag-cis-hooks"));
    }

    #[test]
    fn pinned_keeps_named_stages() {
        let (epel, mf_epel) = make_repos_fragment("epel", "aaa111");
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output = generate_containerfile(
            &manifest,
            &[epel],
            Some("sha256:base123"),
            &empty_dedup(),
            false,
        )
        .unwrap();
        // Named FROM stage and named COPY ref for repo files
        assert!(output.contains("FROM quay.io/test/epel@sha256:aaa111 AS frag-epel"));
        assert!(output.contains("COPY --from=frag-epel /fragment/tree/etc/yum.repos.d/"));
    }

    // --- OCP mode tests ---

    #[test]
    fn ocp_uses_from_configs_as_final() {
        let (epel, mf_epel) = make_unpinned_repos_fragment("epel");
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output =
            generate_containerfile(&manifest, &[epel], None, &empty_dedup(), true).unwrap();
        assert!(output.contains("FROM configs AS final"));
        // Must not contain the standalone base image
        assert!(!output.contains("FROM registry.redhat.io"));
    }

    #[test]
    fn ocp_omits_header_comments() {
        let (epel, mf_epel) = make_unpinned_repos_fragment("epel");
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output =
            generate_containerfile(&manifest, &[epel], None, &empty_dedup(), true).unwrap();
        assert!(!output.contains("# Generated by"));
        assert!(!output.contains("# Fragments:"));
        assert!(!output.contains("# Override summary"));
    }

    #[test]
    fn ocp_omits_section_comments() {
        let (epel, mf_epel) = make_unpinned_repos_fragment("epel");
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output =
            generate_containerfile(&manifest, &[epel], None, &empty_dedup(), true).unwrap();
        assert!(!output.contains("# ---"));
    }

    #[test]
    fn ocp_unpinned_uses_inline_refs() {
        let (epel, mf_epel) = make_unpinned_repos_fragment("epel");
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output =
            generate_containerfile(&manifest, &[epel], None, &empty_dedup(), true).unwrap();
        assert!(output.contains("COPY --from=quay.io/test/epel:10 /fragment/tree/etc/yum.repos.d/"));
        assert!(!output.contains("AS frag-"));
    }

    #[test]
    fn ocp_pinned_uses_named_stages() {
        let (epel, mf_epel) = make_repos_fragment("epel", "aaa111");
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output = generate_containerfile(
            &manifest,
            &[epel],
            Some("sha256:base123"),
            &empty_dedup(),
            true,
        )
        .unwrap();
        // Named stages before FROM configs AS final
        assert!(output.contains("FROM quay.io/test/epel@sha256:aaa111 AS frag-epel"));
        assert!(output.contains("FROM configs AS final"));
        assert!(output.contains("COPY --from=frag-epel /fragment/tree/etc/yum.repos.d/"));
        // Fragment stages must appear before the main stage
        let stage_pos = output.find("AS frag-epel").unwrap();
        let final_pos = output.find("FROM configs AS final").unwrap();
        assert!(stage_pos < final_pos);
    }

    #[test]
    fn ocp_has_preset_apply_and_lint() {
        let (epel, mf_epel) = make_unpinned_repos_fragment("epel");
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output =
            generate_containerfile(&manifest, &[epel], None, &empty_dedup(), true).unwrap();
        assert!(output.contains("systemctl preset-all"));
        assert!(output.contains("bootc container lint"));
    }

    #[test]
    fn multiple_hooks_run_in_alphabetical_order() {
        let mut loaded = LoadedFragment {
            fragment: Fragment {
                name: "multi-hook".to_string(),
                version: "1.0".into(),
                description: "test".into(),
                vendor: None,
                phase: FragmentPhase::Config,
                provides: FragmentProvides { repos: vec![] },
                packages: FragmentPackages { available: vec![] },
                conflicts: FragmentConflicts { fragments: vec![] },
            },
            tree_paths: vec![],
            hook_paths: vec![
                PathBuf::from("03-final.sh"),
                PathBuf::from("01-first.bash"),
                PathBuf::from("02-second.sh"),
            ],
            source: FragmentSource::Registry {
                image_ref: "quay.io/test/multi-hook:1.0".into(),
            },
            resolved_digest: None,
            manifest_index: 0,
            repo_file_contents: std::collections::HashMap::new(),
        };
        loaded.hook_paths.sort(); // Simulate what loader does
        let manifest_frag = ManifestFragment {
            image: "quay.io/test/multi-hook:1.0".into(),
            packages: vec![],
            mirror: None,
        };
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![manifest_frag],
        };
        let output =
            generate_containerfile(&manifest, &[loaded], None, &empty_dedup(), false).unwrap();

        // Verify all three hooks are present in the RUN command
        assert!(output.contains("/tmp/frag-multi-hook-hooks/01-first.bash"));
        assert!(output.contains("/tmp/frag-multi-hook-hooks/02-second.sh"));
        assert!(output.contains("/tmp/frag-multi-hook-hooks/03-final.sh"));

        // Verify alphabetical ordering by checking positions
        let first_pos = output
            .find("/tmp/frag-multi-hook-hooks/01-first.bash")
            .unwrap();
        let second_pos = output
            .find("/tmp/frag-multi-hook-hooks/02-second.sh")
            .unwrap();
        let third_pos = output
            .find("/tmp/frag-multi-hook-hooks/03-final.sh")
            .unwrap();
        assert!(first_pos < second_pos);
        assert!(second_pos < third_pos);
    }

    #[test]
    fn config_fragment_generates_tree_copy() {
        let (mut cis, mf_cis) = make_config_fragment("cis", "bbb222");
        cis.manifest_index = 0;
        cis.tree_paths.push(PathBuf::from(
            "tree/usr/lib/systemd/system-preset/50-hardening.preset",
        ));
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_cis],
        };
        let output = generate_containerfile(
            &manifest,
            &[cis],
            Some("sha256:base123"),
            &empty_dedup(),
            false,
        )
        .unwrap();
        assert!(
            output.contains("COPY --from=frag-cis /fragment/tree/ /"),
            "expected config COPY line in output:\n{}",
            output
        );
    }

    #[test]
    fn mixed_repos_and_config_full_content_ordering() {
        let (epel, mf_epel) = make_repos_fragment("epel", "aaa111");
        let (mut cis, mf_cis) = make_config_fragment("cis", "bbb222");
        cis.manifest_index = 1;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel, mf_cis],
        };
        let output = generate_containerfile(
            &manifest,
            &[epel, cis],
            Some("sha256:base123"),
            &empty_dedup(),
            false,
        )
        .unwrap();
        // Verify full content ordering: repo COPY -> dnf install -> config COPY -> hook COPY
        let repo_copy = output
            .find("COPY --from=frag-epel /fragment/tree/etc/yum.repos.d/")
            .expect("missing repo COPY");
        let dnf_install = output.find("dnf install -y").expect("missing dnf install");
        let config_copy = output
            .find("COPY --from=frag-cis /fragment/tree/ /")
            .expect("missing config COPY");
        let hook_copy = output
            .find("COPY --from=frag-cis /fragment/hooks/")
            .expect("missing hook COPY");
        assert!(repo_copy < dnf_install);
        assert!(dnf_install < config_copy);
        assert!(config_copy < hook_copy);
    }

    #[test]
    fn overlapping_tree_paths_produce_collision_comment() {
        let shared_path = PathBuf::from("tree/etc/sysctl.d/99-net.conf");
        let (mut frag_a, mf_a) = make_config_fragment("net-tuning", "aaa");
        frag_a.tree_paths = vec![shared_path.clone()];
        frag_a.hook_paths = vec![];
        let (mut frag_b, mf_b) = make_config_fragment("perf-tuning", "bbb");
        frag_b.tree_paths = vec![shared_path];
        frag_b.hook_paths = vec![];
        frag_b.manifest_index = 1;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_a, mf_b],
        };
        let output = generate_containerfile(
            &manifest,
            &[frag_a, frag_b],
            Some("sha256:base123"),
            &empty_dedup(),
            false,
        )
        .unwrap();
        assert!(
            output.contains("collision"),
            "expected collision comment in header:\n{}",
            output
        );
        assert!(output.contains("net-tuning"));
        assert!(output.contains("perf-tuning"));
    }

    #[test]
    fn ocp_hooks_without_section_comments() {
        let (mut cis, mf_cis) = make_unpinned_config_fragment("cis");
        cis.manifest_index = 0;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_cis],
        };
        let output = generate_containerfile(&manifest, &[cis], None, &empty_dedup(), true).unwrap();
        // Hooks should appear in OCP output
        assert!(
            output.contains("/fragment/hooks/"),
            "expected hook COPY in OCP output:\n{}",
            output
        );
        assert!(
            output.contains("configure.sh"),
            "expected hook execution in OCP output:\n{}",
            output
        );
        // No section comment headers in OCP mode
        assert!(
            !output.contains("# ---"),
            "OCP output should not contain section comments:\n{}",
            output
        );
    }

    #[test]
    fn hooks_never_in_copy_instruction() {
        // Unpinned standalone
        let (mut cis, mf_cis) = make_unpinned_config_fragment("cis");
        cis.manifest_index = 0;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_cis.clone()],
        };
        let standalone = generate_containerfile(
            &manifest,
            &[cis.clone()],
            None,
            &empty_dedup(),
            false,
        )
        .unwrap();
        for line in standalone.lines() {
            if line.starts_with("COPY") {
                assert!(
                    !line.contains("hooks"),
                    "hooks/ must not appear in COPY instruction (standalone):\n{}",
                    line
                );
            }
        }

        // Unpinned OCP
        let ocp_output = generate_containerfile(
            &manifest,
            &[cis],
            None,
            &empty_dedup(),
            true,
        )
        .unwrap();
        for line in ocp_output.lines() {
            if line.starts_with("COPY") {
                assert!(
                    !line.contains("hooks"),
                    "hooks/ must not appear in COPY instruction (OCP):\n{}",
                    line
                );
            }
        }

        // Pinned standalone
        let (mut pinned_cis, mf_pinned) = make_config_fragment("cis", "bbb222");
        pinned_cis.manifest_index = 0;
        let pinned_manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_pinned],
        };
        let pinned_output = generate_containerfile(
            &pinned_manifest,
            &[pinned_cis],
            Some("sha256:base123"),
            &empty_dedup(),
            false,
        )
        .unwrap();
        for line in pinned_output.lines() {
            if line.starts_with("COPY") {
                assert!(
                    !line.contains("hooks"),
                    "hooks/ must not appear in COPY instruction (pinned):\n{}",
                    line
                );
            }
        }
    }
}
