use anyhow::Result;
use std::fmt::Write;

use crate::fragment::is_repo_path;
use crate::loader::LoadedFragment;
use crate::manifest::{FragmentSource, Manifest};
use crate::validate::DeduplicationResult;

/// Split a container image reference into (name, optional_tag).
///
/// The tag separator is the last `:` that appears after the last `/`.
/// This correctly handles registry ports (e.g., `localhost:5000/image:tag`).
/// Returns `(full_ref, None)` when no tag is present or the ref already
/// contains a digest (`@`).
pub fn split_image_ref(image_ref: &str) -> (&str, Option<&str>) {
    // Digests are not tags — leave them alone
    if image_ref.contains('@') {
        return (image_ref, None);
    }

    let colon_search_start = image_ref.rfind('/').map(|p| p + 1).unwrap_or(0);

    match image_ref[colon_search_start..].find(':') {
        Some(offset) => {
            let colon_pos = colon_search_start + offset;
            (&image_ref[..colon_pos], Some(&image_ref[colon_pos + 1..]))
        }
        None => (image_ref, None),
    }
}

pub fn generate_containerfile(
    manifest: &Manifest,
    fragments: &[LoadedFragment],
    base_digest: Option<&str>,
    dedup: &DeduplicationResult,
) -> Result<String> {
    let mut out = String::new();

    // Header
    writeln!(out, "# Generated by bootc-assemble v0.1.0")?;
    writeln!(out, "# Manifest: bootc-assemble.yaml")?;

    let frag_summary: Vec<String> = fragments
        .iter()
        .map(|f| {
            format!(
                "{} ({})",
                f.fragment.name,
                match f.fragment.phase {
                    crate::fragment::FragmentPhase::Repos => "repos",
                    crate::fragment::FragmentPhase::Config => "config",
                }
            )
        })
        .collect();
    writeln!(out, "# Fragments: {}", frag_summary.join(", "))?;

    // Resolved digests (only when --pin-digests is used)
    let has_digests = base_digest.is_some() || fragments.iter().any(|f| f.resolved_digest.is_some());
    if has_digests {
        writeln!(out, "# Resolved digests:")?;
        if let Some(d) = base_digest {
            writeln!(out, "#   base: {}@{}", manifest.base, d)?;
        }
        for loaded in fragments {
            let mf = &manifest.fragments[loaded.manifest_index];
            if let Some(d) = &loaded.resolved_digest {
                writeln!(out, "#   {}: {}@{}", loaded.fragment.name, mf.image, d)?;
            }
        }
    }

    // Compute override summary — detect file path collisions
    let mut path_owners: std::collections::HashMap<String, Vec<String>> =
        std::collections::HashMap::new();
    for loaded in fragments {
        for p in &loaded.tree_paths {
            if p.to_string_lossy().starts_with("tree/") {
                let dest = p
                    .strip_prefix("tree")
                    .unwrap_or(p)
                    .to_string_lossy()
                    .to_string();
                path_owners
                    .entry(dest)
                    .or_default()
                    .push(loaded.fragment.name.clone());
            }
        }
    }
    let collisions: Vec<_> = path_owners
        .iter()
        .filter(|(_, owners)| owners.len() > 1)
        .collect();
    if collisions.is_empty() {
        writeln!(out, "# Override summary: no file path collisions detected")?;
    } else {
        writeln!(
            out,
            "# Override summary: {} file path collision(s) detected",
            collisions.len()
        )?;
        for (path, owners) in &collisions {
            writeln!(
                out,
                "#   {} — written by: {} (last wins)",
                path,
                owners.join(", ")
            )?;
        }
    }
    writeln!(out)?;

    // Fragment FROM stages
    writeln!(out, "# --- Fragment stages ---")?;
    for loaded in fragments {
        let FragmentSource::Registry { ref image_ref } = loaded.source;
        writeln!(out, "FROM {} AS frag-{}", image_ref, loaded.fragment.name)?;
    }
    writeln!(out)?;

    // Base
    writeln!(out, "# --- Base ---")?;
    let base_ref = if let Some(d) = base_digest {
        let (base_name, _tag) = split_image_ref(&manifest.base);
        format!("{}@{}", base_name, d)
    } else {
        manifest.base.clone()
    };
    writeln!(out, "FROM {}", base_ref)?;
    writeln!(out)?;

    // Copy fragment files — one COPY per fragment
    let has_tree_content = fragments
        .iter()
        .any(|f| f.tree_paths.iter().any(|p| p.to_string_lossy().starts_with("tree/")));
    if has_tree_content {
        writeln!(out, "# --- Fragment files ---")?;
        for loaded in fragments {
            let has_tree = loaded
                .tree_paths
                .iter()
                .any(|p| p.to_string_lossy().starts_with("tree/"));
            if !has_tree {
                continue;
            }
            writeln!(
                out,
                "COPY --from=frag-{} /fragment/tree/ /",
                loaded.fragment.name
            )?;
        }

        // Mirror rewrites (must follow the COPYs)
        for loaded in fragments {
            let mf = &manifest.fragments[loaded.manifest_index];
            if let Some(mirror_url) = &mf.mirror {
                let repo_files: Vec<_> = loaded
                    .tree_paths
                    .iter()
                    .filter(|p| p.to_string_lossy().contains("yum.repos.d"))
                    .filter_map(|p| {
                        p.file_name()
                            .map(|f| format!("/etc/yum.repos.d/{}", f.to_string_lossy()))
                    })
                    .collect();
                for repo_file in &repo_files {
                    writeln!(
                        out,
                        "RUN sed -i 's|^baseurl=.*|baseurl={}|; s|^metalink=|#metalink=|; s|^mirrorlist=|#mirrorlist=|' {}",
                        mirror_url, repo_file
                    )?;
                }
            }
        }
        writeln!(out)?;
    }

    // Packages
    let mut seen = std::collections::HashSet::new();
    let all_packages: Vec<String> = manifest
        .fragments
        .iter()
        .flat_map(|f| f.packages.iter().cloned())
        .filter(|p| seen.insert(p.clone()))
        .collect();
    if !all_packages.is_empty() {
        writeln!(out, "# --- Packages ---")?;
        writeln!(out, "RUN dnf install -y \\")?;
        for pkg in &all_packages {
            writeln!(out, "        {} \\", pkg)?;
        }
        writeln!(out, "    && dnf clean all")?;
        writeln!(out)?;
    }

    // Scripts (must run after packages are installed)
    let script_fragments: Vec<_> = fragments
        .iter()
        .filter(|f| f.has_configure_script)
        .collect();
    if !script_fragments.is_empty() {
        writeln!(out, "# --- Scripts ---")?;
        for loaded in &script_fragments {
            writeln!(
                out,
                "COPY --from=frag-{name} /fragment/scripts/configure.sh /tmp/frag-{name}-configure.sh",
                name = loaded.fragment.name
            )?;
            writeln!(
                out,
                "RUN /tmp/frag-{name}-configure.sh && rm -f /tmp/frag-{name}-configure.sh",
                name = loaded.fragment.name
            )?;
        }
        writeln!(out)?;
    }

    // Phase: preset-apply (35)
    writeln!(out, "# --- Phase: preset-apply (35) ---")?;
    writeln!(
        out,
        "RUN systemctl preset-all --preset-mode=enable-only 2>/dev/null || true"
    )?;
    writeln!(out)?;

    // Phase: validation (90)
    writeln!(out, "# --- Phase: validation (90) ---")?;
    writeln!(out, "RUN bootc container lint")?;

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    use crate::fragment::{
        Fragment, FragmentConflicts, FragmentPackages, FragmentPhase, FragmentProvides,
    };
    use crate::loader::LoadedFragment;
    use crate::manifest::{FragmentSource, Manifest, ManifestFragment};

    fn make_repos_fragment(name: &str, digest: &str) -> (LoadedFragment, ManifestFragment) {
        let loaded = LoadedFragment {
            fragment: Fragment {
                name: name.to_string(),
                version: "10".into(),
                description: "test".into(),
                vendor: None,
                phase: FragmentPhase::Repos,
                provides: FragmentProvides {
                    repos: vec![name.to_string()],
                },
                packages: FragmentPackages { available: vec![] },
                conflicts: FragmentConflicts { fragments: vec![] },
            },
            tree_paths: vec![
                PathBuf::from("tree/etc/yum.repos.d/test.repo"),
                PathBuf::from("tree/etc/pki/rpm-gpg/RPM-GPG-KEY-test"),
            ],
            has_configure_script: false,
            source: FragmentSource::Registry {
                image_ref: format!("quay.io/test/{}@sha256:{}", name, digest),
            },
            resolved_digest: Some(format!("sha256:{}", digest)),
            manifest_index: 0,
            repo_file_contents: std::collections::HashMap::new(),
        };
        let manifest_frag = ManifestFragment {
            image: format!("quay.io/test/{}:10", name),
            packages: vec!["htop".into()],
            mirror: None,
        };
        (loaded, manifest_frag)
    }

    fn make_config_fragment(name: &str, digest: &str) -> (LoadedFragment, ManifestFragment) {
        let loaded = LoadedFragment {
            fragment: Fragment {
                name: name.to_string(),
                version: "2.1".into(),
                description: "test".into(),
                vendor: None,
                phase: FragmentPhase::Config,
                provides: FragmentProvides { repos: vec![] },
                packages: FragmentPackages { available: vec![] },
                conflicts: FragmentConflicts { fragments: vec![] },
            },
            tree_paths: vec![PathBuf::from("tree/usr/lib/sysctl.d/99-hardening.conf")],
            has_configure_script: true,
            source: FragmentSource::Registry {
                image_ref: format!("quay.io/test/{}@sha256:{}", name, digest),
            },
            resolved_digest: Some(format!("sha256:{}", digest)),
            manifest_index: 0,
            repo_file_contents: std::collections::HashMap::new(),
        };
        let manifest_frag = ManifestFragment {
            image: format!("quay.io/test/{}:2.1", name),
            packages: vec![],
            mirror: None,
        };
        (loaded, manifest_frag)
    }

    fn empty_dedup() -> crate::validate::DeduplicationResult {
        crate::validate::DeduplicationResult {
            deduplicated_repos: std::collections::HashMap::new(),
        }
    }

    #[test]
    fn generated_output_contains_digest_pinned_from() {
        let (epel, mf_epel) = make_repos_fragment("epel", "aaa111");
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output =
            generate_containerfile(&manifest, &[epel], Some("sha256:base123"), &empty_dedup())
                .unwrap();
        assert!(output.contains("@sha256:aaa111"));
        assert!(output.contains("@sha256:base123"));
        assert!(!output.contains("FROM quay.io/test/epel:10 AS"));
    }

    #[test]
    fn generated_output_has_section_ordering() {
        let (epel, mf_epel) = make_repos_fragment("epel", "aaa111");
        let (mut cis, mf_cis) = make_config_fragment("cis", "bbb222");
        cis.manifest_index = 1;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel, mf_cis],
        };
        let output = generate_containerfile(
            &manifest,
            &[epel, cis],
            Some("sha256:base123"),
            &empty_dedup(),
        )
        .unwrap();
        let files_pos = output.find("Fragment files").unwrap();
        let packages_pos = output.find("Packages").unwrap();
        let scripts_pos = output.find("Scripts").unwrap();
        let preset_pos = output.find("preset-apply").unwrap();
        let validation_pos = output.find("validation").unwrap();
        assert!(files_pos < packages_pos);
        assert!(packages_pos < scripts_pos);
        assert!(scripts_pos < preset_pos);
        assert!(preset_pos < validation_pos);
    }

    #[test]
    fn generated_output_batches_packages() {
        let (epel, mf_epel) = make_repos_fragment("epel", "aaa111");
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output =
            generate_containerfile(&manifest, &[epel], Some("sha256:base123"), &empty_dedup())
                .unwrap();
        assert!(output.contains("dnf install -y"));
        assert!(output.contains("htop"));
    }

    #[test]
    fn generated_output_has_preset_apply() {
        let (mut cis, mf_cis) = make_config_fragment("cis", "bbb222");
        cis.manifest_index = 0;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_cis],
        };
        let output =
            generate_containerfile(&manifest, &[cis], Some("sha256:base123"), &empty_dedup())
                .unwrap();
        assert!(output.contains("systemctl preset-all --preset-mode=enable-only"));
    }

    #[test]
    fn generated_output_has_bootc_lint() {
        let (mut cis, mf_cis) = make_config_fragment("cis", "bbb222");
        cis.manifest_index = 0;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_cis],
        };
        let output =
            generate_containerfile(&manifest, &[cis], Some("sha256:base123"), &empty_dedup())
                .unwrap();
        assert!(output.contains("bootc container lint"));
    }

    #[test]
    fn no_packages_phase_when_no_packages() {
        let (mut cis, mf_cis) = make_config_fragment("cis", "bbb222");
        cis.manifest_index = 0;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_cis],
        };
        let output =
            generate_containerfile(&manifest, &[cis], Some("sha256:base123"), &empty_dedup())
                .unwrap();
        assert!(!output.contains("dnf install"));
    }

    #[test]
    fn mirror_generates_sed_rewrite() {
        let (epel, mut mf_epel) = make_repos_fragment("epel", "aaa111");
        mf_epel.mirror = Some("https://mirror.corp/epel/".into());
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output =
            generate_containerfile(&manifest, &[epel], Some("sha256:base123"), &empty_dedup())
                .unwrap();
        assert!(output.contains("sed"));
        assert!(output.contains("https://mirror.corp/epel/"));
    }

    #[test]
    fn repo_dedup_skips_non_canonical_provider() {
        let (epel, mf_epel) = make_repos_fragment("epel", "aaa111");
        let (mut node_exp, mf_node) = make_repos_fragment("node-exporter", "ccc333");
        node_exp.manifest_index = 1;
        let manifest = Manifest {
            base: "registry.redhat.io/rhel10/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel, mf_node],
        };
        let mut dedup = empty_dedup();
        dedup
            .deduplicated_repos
            .insert("epel".to_string(), "epel".to_string());
        dedup
            .deduplicated_repos
            .insert("node-exporter".to_string(), "node-exporter".to_string());
        let output =
            generate_containerfile(&manifest, &[epel, node_exp], Some("sha256:base123"), &dedup)
                .unwrap();
        // epel is canonical for its own repo — its COPY should appear
        let epel_copy_count = output.matches("COPY --from=frag-epel").count();
        assert!(epel_copy_count > 0);
    }

    #[test]
    fn split_image_ref_standard_registry() {
        let (name, tag) = super::split_image_ref("registry.redhat.io/rhel9/rhel-bootc:9.4");
        assert_eq!(name, "registry.redhat.io/rhel9/rhel-bootc");
        assert_eq!(tag, Some("9.4"));
    }

    #[test]
    fn split_image_ref_with_port() {
        let (name, tag) = super::split_image_ref("localhost:5000/myimage:latest");
        assert_eq!(name, "localhost:5000/myimage");
        assert_eq!(tag, Some("latest"));
    }

    #[test]
    fn split_image_ref_quay_with_tag() {
        let (name, tag) = super::split_image_ref("quay.io/centos-bootc/centos-bootc:stream9");
        assert_eq!(name, "quay.io/centos-bootc/centos-bootc");
        assert_eq!(tag, Some("stream9"));
    }

    #[test]
    fn split_image_ref_no_tag() {
        let (name, tag) = super::split_image_ref("registry.redhat.io/rhel9/rhel-bootc");
        assert_eq!(name, "registry.redhat.io/rhel9/rhel-bootc");
        assert_eq!(tag, None);
    }

    #[test]
    fn split_image_ref_with_digest() {
        let (name, tag) = super::split_image_ref("quay.io/image@sha256:abc123");
        assert_eq!(name, "quay.io/image@sha256:abc123");
        assert_eq!(tag, None);
    }

    #[test]
    fn split_image_ref_port_no_tag() {
        let (name, tag) = super::split_image_ref("localhost:5000/myimage");
        assert_eq!(name, "localhost:5000/myimage");
        assert_eq!(tag, None);
    }

    #[test]
    fn split_image_ref_simple_with_tag() {
        let (name, tag) = super::split_image_ref("nginx:latest");
        assert_eq!(name, "nginx");
        assert_eq!(tag, Some("latest"));
    }

    #[test]
    fn split_image_ref_simple_no_tag() {
        let (name, tag) = super::split_image_ref("nginx");
        assert_eq!(name, "nginx");
        assert_eq!(tag, None);
    }

    #[test]
    fn base_image_with_port_generates_correct_from() {
        let (epel, mf_epel) = make_repos_fragment("epel", "aaa111");
        let manifest = Manifest {
            base: "localhost:5000/rhel-bootc:10.0".into(),
            fragments: vec![mf_epel],
        };
        let output =
            generate_containerfile(&manifest, &[epel], Some("sha256:base123"), &empty_dedup())
                .unwrap();
        // Must preserve the port in the pinned ref
        assert!(output.contains("FROM localhost:5000/rhel-bootc@sha256:base123"));
    }
}
