//! Self-contained output mode: materializes fragment tree/hooks payload
//! into a local build context next to the generated Containerfile, then
//! packages the result as a sibling tarball. The emitted Containerfile
//! references no registry image except the base.

use crate::loader::LoadedFragment;
use crate::manifest::FragmentSource;
use crate::mount::MountMaterialization;
use anyhow::{bail, Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

/// Filename of the sentinel marker written into every self-contained output
/// directory. Its presence, not directory contents, is the ownership proof
/// `check_target_dir_safe` relies on: a directory containing a `Containerfile`
/// and `fragments/` for reasons of its own (a false positive under a
/// content-only heuristic) will not coincidentally contain this exact
/// dotfile. The sentinel is a regular file within `<dir>`, so it is part of
/// the committed tree and the packaged archive like everything else the tool
/// writes; a directory checked out from git with the sentinel intact is
/// exactly as regenerable as the one that produced it.
pub const SENTINEL_FILENAME: &str = ".osfragment-assemble";

/// Contents written to the sentinel file: tool name and version, nothing
/// else. Presence is what `check_target_dir_safe` checks, not this exact
/// text, so the format has no compatibility contract to keep.
pub fn sentinel_contents() -> String {
    format!("osfragment-assemble v{}\n", env!("CARGO_PKG_VERSION"))
}

/// Entries the tool itself may have written to a self-contained output
/// directory in a prior run. A directory is safe to regenerate only if
/// every entry it contains is one of these.
const TOOL_GENERATED_ENTRIES: &[&str] = &[
    "Containerfile",
    "manifest.yaml",
    "fragments",
    SENTINEL_FILENAME,
];

/// Permission mode applied to the output directory after the staging swap,
/// overriding the 0700 the staging tempdir was created with. `<dir>` is a
/// handoff artifact (committed to git, packaged into a tarball for other
/// pipelines), not a private scratch directory, so it and the resulting
/// tar entries should be normally readable.
const OUTPUT_DIR_MODE: u32 = 0o755;

/// Refuse to regenerate into a directory that holds anything the tool did
/// not write itself. Absent and empty directories are always safe; a
/// directory containing the sentinel file (`.osfragment-assemble`) and no
/// entries outside the tool-generated set is recognized as tool-generated
/// from a prior run and is safe to delete and recreate. The sentinel, not
/// the presence of `Containerfile`/`fragments/` alone, is what proves
/// ownership: those names are common enough that a user's own directory
/// could coincidentally match them, but not this exact dotfile.
pub fn check_target_dir_safe(dir: &Path) -> Result<()> {
    if !dir.exists() {
        return Ok(());
    }
    if !dir.is_dir() {
        bail!(
            "--self-contained target {} exists and is not a directory; point \
             --self-contained at a directory path instead",
            dir.display()
        );
    }

    let mut entries = Vec::new();
    for entry in fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))? {
        entries.push(entry?.file_name().to_string_lossy().to_string());
    }

    if entries.is_empty() {
        return Ok(());
    }

    let all_recognized = entries
        .iter()
        .all(|e| TOOL_GENERATED_ENTRIES.contains(&e.as_str()));
    let has_sentinel = entries.iter().any(|e| e == SENTINEL_FILENAME);

    if all_recognized && has_sentinel {
        return Ok(());
    }

    bail!(
        "--self-contained target {} already exists and was not generated by this tool \
         (expected the {} sentinel plus Containerfile, manifest.yaml, fragments/, and \
         nothing else); point --self-contained at a new or empty directory",
        dir.display(),
        SENTINEL_FILENAME
    );
}

/// Refuse a target path that is itself a symlink, before anything
/// destructive runs.
///
/// Every other check here goes through `exists()`/`is_dir()`, which resolve
/// a symlink to its target. That makes a symlinked `<dir>` ambiguous in a
/// way worth refusing outright rather than resolving silently: the safety
/// check would read the *target's* contents to authorize the write, while
/// the path actually removed and replaced is the link. A dangling symlink
/// is the mirror image, reading as absent and failing only at the final
/// rename. Both are refused here with a message that names the symlink.
fn check_target_not_symlink(dir: &Path) -> Result<()> {
    let is_symlink = fs::symlink_metadata(dir).is_ok_and(|m| m.file_type().is_symlink());
    if is_symlink {
        bail!(
            "--self-contained target {} is a symlink; point it at a real directory path \
             (this mode replaces the target directory wholesale and will not write \
             through a symlink)",
            dir.display()
        );
    }
    Ok(())
}

/// Materialize the self-contained output: fragment tree/hooks payload,
/// the generated Containerfile, and a copy of the input manifest.
///
/// Builds into a staging directory next to `dir` first and swaps it into
/// place only after every fragment materializes successfully, so a
/// registry failure partway through never leaves a partial tree at `dir`.
///
/// The staging directory is reclaimed automatically on every failure up to
/// and including the removal of an existing `dir`, leaving `dir` untouched.
/// That is where the guarantee ends: `keep()` disarms the cleanup so the
/// tree can survive the rename, so a failing rename leaves the complete
/// output at the staging path and says so in its error rather than
/// discarding minutes of registry work.
///
/// `materialize` is the per-fragment materialization call; production
/// code always passes `crate::loader::materialize_fragment` (see
/// `write_output` below), tests substitute a network-free stub.
fn write_output_with(
    dir: &Path,
    manifest_path: &Path,
    containerfile: &str,
    fragments: &[LoadedFragment],
    materialize: impl Fn(&str, &Path) -> Result<()>,
) -> Result<()> {
    check_target_not_symlink(dir)?;
    check_target_dir_safe(dir)?;

    let parent = dir
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;

    // Staging MUST live in <dir>'s parent, not $TMPDIR: fs::rename below is
    // only atomic within a filesystem, and the whole no-partial-state
    // guarantee rests on that rename being atomic. Relocating this breaks
    // the contract silently, with no test failure.
    let staging = tempfile::Builder::new()
        .prefix(".osfragment-assemble-staging-")
        .tempdir_in(parent)
        .context("creating staging directory for self-contained output")?;

    fs::write(staging.path().join("Containerfile"), containerfile)
        .context("writing staged Containerfile")?;
    fs::copy(manifest_path, staging.path().join("manifest.yaml")).with_context(|| {
        format!(
            "copying manifest {} into staged output",
            manifest_path.display()
        )
    })?;
    // The sentinel is a regular file in the staged tree, so it is part of
    // the committed tree and the archive like everything else here, and
    // check_target_dir_safe recognizes it on the next regeneration.
    fs::write(staging.path().join(SENTINEL_FILENAME), sentinel_contents())
        .context("writing sentinel marker")?;

    let staged_fragments = staging.path().join("fragments");
    fs::create_dir_all(&staged_fragments)
        .with_context(|| format!("creating {}", staged_fragments.display()))?;

    for loaded in fragments {
        let FragmentSource::Registry { ref image_ref } = loaded.source;
        let dest = staged_fragments.join(&loaded.fragment.name);
        materialize(image_ref, &dest)
            .with_context(|| format!("materializing fragment '{}'", loaded.fragment.name))?;
    }

    // The staging tempdir was created at 0700. Normalize it to a normal,
    // world-readable mode: `<dir>` is a handoff artifact (committed to git,
    // packaged into the tarball below), not a private scratch directory, and
    // a 0700 top-level entry would carry into every tar header
    // create_archive writes. The mode is set on the staging path, before
    // keep(), rather than on `<dir>` after the rename: it survives the
    // rename either way, and doing it here keeps the rename the last
    // fallible step in this function.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(staging.path(), fs::Permissions::from_mode(OUTPUT_DIR_MODE))
            .with_context(|| format!("normalizing permissions on {}", staging.path().display()))?;
    }

    // Re-check immediately before the destructive step: the checks above ran
    // before minutes of registry I/O, and <dir> may have changed since.
    check_target_not_symlink(dir)?;
    check_target_dir_safe(dir)?;

    if dir.exists() {
        fs::remove_dir_all(dir).with_context(|| format!("removing existing {}", dir.display()))?;
    }
    // TempDir::into_path() is deprecated in favor of keep() as of tempfile
    // 3.14; both disarm the automatic cleanup so the directory survives the
    // rename below. keep() is the non-deprecated spelling.
    let staging_path = staging.keep();
    fs::rename(&staging_path, dir).with_context(|| {
        format!(
            "moving staged output {} into {}; the generated output is complete \
             and left at the staging path",
            staging_path.display(),
            dir.display()
        )
    })?;

    Ok(())
}

/// Materialize the self-contained output at `dir` using the real registry
/// pull path.
pub fn write_output(
    dir: &Path,
    manifest_path: &Path,
    containerfile: &str,
    fragments: &[LoadedFragment],
) -> Result<()> {
    write_output_with(
        dir,
        manifest_path,
        containerfile,
        fragments,
        |image_ref, dest| {
            crate::loader::materialize_fragment(image_ref, dest, MountMaterialization::Skip)
        },
    )
}

/// Sibling archive path for a self-contained output directory: `<dir>`
/// with `.tar.gz` appended to its final component, e.g. `build/context` ->
/// `build/context.tar.gz`. Derives the name from `Path::file_name()`
/// rather than raw `OsStr` concatenation, so a trailing separator (e.g.
/// `--self-contained out/`, what shell completion produces for an existing
/// directory) still yields the sibling `out.tar.gz` rather than a hidden
/// `.tar.gz` file inside `out/`.
fn archive_path_for(dir: &Path) -> PathBuf {
    let file_name = dir.file_name().unwrap_or(dir.as_os_str());
    let mut archive_name = file_name.to_os_string();
    archive_name.push(".tar.gz");
    match dir.parent() {
        Some(parent) if !parent.as_os_str().is_empty() => parent.join(archive_name),
        _ => PathBuf::from(archive_name),
    }
}

/// Package `dir` as a sibling `.tar.gz`, with a single top-level directory
/// named after `dir`'s basename so extraction is predictable regardless of
/// where the archive is unpacked. Returns the archive's path.
///
/// Builds the gzip/tar stream into a temp file beside the destination and
/// renames it into place as the last fallible step, mirroring
/// `write_output_with`'s staging contract. On any failure (a walk error, a
/// full disk, the gzip/tar finish failing) the temp file is dropped and
/// reclaimed automatically, and a pre-existing `<dir>.tar.gz` is left
/// untouched rather than truncated. The rename also replaces a symlinked
/// `<dir>.tar.gz` outright instead of writing through it.
pub fn create_archive(dir: &Path) -> Result<PathBuf> {
    let file_name = dir
        .file_name()
        .ok_or_else(|| anyhow::anyhow!("{} has no directory name", dir.display()))?;
    let archive_path = archive_path_for(dir);
    let parent = archive_path
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));

    // Staging MUST live in the archive's parent, not $TMPDIR: persist below
    // is only atomic within a filesystem, and the whole no-partial-state
    // guarantee rests on that persist being atomic. Relocating this breaks
    // the contract silently, with no test failure.
    let staged = tempfile::Builder::new()
        .prefix(".osfragment-assemble-archive-")
        .tempfile_in(parent)
        .with_context(|| format!("creating staging archive in {}", parent.display()))?;

    let encoder = flate2::write::GzEncoder::new(staged, flate2::Compression::default());
    let mut builder = tar::Builder::new(encoder);
    builder.append_dir_all(file_name, dir).with_context(|| {
        format!(
            "archiving {} into {}",
            dir.display(),
            archive_path.display()
        )
    })?;
    let staged = builder
        .into_inner()
        .context("finishing tar stream")?
        .finish()
        .context("finishing gzip stream")?;

    staged.persist(&archive_path).map_err(|e| {
        anyhow::anyhow!(
            "moving staged archive into {}: {}",
            archive_path.display(),
            e
        )
    })?;

    Ok(archive_path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn absent_directory_is_safe() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("does-not-exist-yet");
        assert!(check_target_dir_safe(&dir).is_ok());
    }

    #[test]
    fn empty_directory_is_safe() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("empty");
        fs::create_dir(&dir).unwrap();
        assert!(check_target_dir_safe(&dir).is_ok());
    }

    #[test]
    fn tool_generated_directory_is_safe() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("prior-run");
        fs::create_dir_all(dir.join("fragments/epel")).unwrap();
        fs::write(dir.join("Containerfile"), "FROM x\n").unwrap();
        fs::write(dir.join("manifest.yaml"), "base: x\n").unwrap();
        fs::write(dir.join(SENTINEL_FILENAME), sentinel_contents()).unwrap();
        assert!(check_target_dir_safe(&dir).is_ok());
    }

    #[test]
    fn existing_file_target_is_refused() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("not-a-dir");
        fs::write(&path, b"user data").unwrap();
        let err = check_target_dir_safe(&path).unwrap_err();
        assert!(err.to_string().contains("is not a directory"));
        assert_eq!(fs::read(&path).unwrap(), b"user data");
    }

    #[test]
    fn foreign_directory_is_refused() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("mine");
        fs::create_dir(&dir).unwrap();
        fs::write(dir.join("README.md"), "not ours").unwrap();
        let err = check_target_dir_safe(&dir).unwrap_err();
        assert!(err.to_string().contains("was not generated by this tool"));
    }

    #[test]
    fn directory_missing_sentinel_is_refused() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("partial");
        fs::create_dir(&dir).unwrap();
        fs::write(dir.join("Containerfile"), "FROM x\n").unwrap();
        let err = check_target_dir_safe(&dir).unwrap_err();
        assert!(err.to_string().contains("was not generated by this tool"));
    }

    #[test]
    fn containerfile_and_fragments_without_sentinel_is_refused() {
        // The exact false positive the sentinel replaces: a user's own
        // directory that happens to contain both a Containerfile and a
        // fragments/ subdirectory for unrelated reasons must not be treated
        // as tool-generated just because a content-only heuristic would
        // have matched it.
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("users-own-project");
        fs::create_dir_all(dir.join("fragments/whatever")).unwrap();
        fs::write(dir.join("Containerfile"), "FROM my-own-base\n").unwrap();
        let err = check_target_dir_safe(&dir).unwrap_err();
        assert!(err.to_string().contains("was not generated by this tool"));
    }

    #[test]
    fn sentinel_present_but_extra_user_file_is_refused() {
        // The sentinel proves the tool wrote *something* here at some
        // point, but an unexpected extra entry alongside it is still
        // refused rather than silently swept up in the next regeneration.
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("prior-run-plus-extra");
        fs::create_dir_all(dir.join("fragments/epel")).unwrap();
        fs::write(dir.join("Containerfile"), "FROM x\n").unwrap();
        fs::write(dir.join(SENTINEL_FILENAME), sentinel_contents()).unwrap();
        fs::write(dir.join("notes.txt"), "my own notes").unwrap();
        let err = check_target_dir_safe(&dir).unwrap_err();
        assert!(err.to_string().contains("was not generated by this tool"));
    }

    fn test_loaded_fragment(name: &str) -> LoadedFragment {
        use crate::fragment::{
            Fragment, FragmentConflicts, FragmentName, FragmentPackages, FragmentProvides,
        };
        LoadedFragment {
            fragment: Fragment {
                name: FragmentName::new(name).expect("test fragment name must be valid"),
                version: "1".into(),
                description: "test".into(),
                vendor: None,
                provides: FragmentProvides { repos: vec![] },
                packages: FragmentPackages { required: vec![] },
                conflicts: FragmentConflicts { fragments: vec![] },
            },
            tree_paths: vec![],
            hook_paths: vec![],
            source: FragmentSource::Registry {
                image_ref: format!("quay.io/test/{}:1", name),
            },
            resolved_digest: None,
            manifest_index: 0,
            repo_file_contents: std::collections::HashMap::new(),
            mount_points: vec![],
            has_mount_dir: false,
            drift_warning: None,
        }
    }

    /// Builds a minimal fragment layer tarball for tests that need to
    /// exercise the real `extract_fragment_payload_to_disk` extractor
    /// without a registry. Mirrors the real layer shape
    /// (`fragment/tree/...`, `fragment/hooks/...`). Takes an explicit mode
    /// per entry (following the `RawEntry`/`create_test_tarball_with_modes`
    /// precedent in `src/loader.rs`) so tests can assert modes survive in
    /// both directions rather than everything landing at one fixed mode.
    fn build_fixture_layer(entries: &[(&str, &[u8], u32)]) -> Vec<u8> {
        let mut buf = Vec::new();
        {
            let enc = flate2::write::GzEncoder::new(&mut buf, flate2::Compression::default());
            let mut tar = tar::Builder::new(enc);
            for (path, data, mode) in entries {
                let mut header = tar::Header::new_gnu();
                header.set_path(path).unwrap();
                header.set_size(data.len() as u64);
                header.set_mode(*mode);
                header.set_cksum();
                tar.append(&header, &data[..]).unwrap();
            }
            tar.into_inner().unwrap().finish().unwrap();
        }
        buf
    }

    #[test]
    fn materialize_and_archive_round_trip_byte_for_byte() {
        // Composes write_output_with (real extract_fragment_payload_to_disk,
        // stubbing only the skopeo pull) with create_archive over the same
        // tree: the spec's single acceptance test 2 (materialize from
        // fixture fragments, then diff the archive against the tree byte
        // for byte), with no network access.
        let epel_layer = build_fixture_layer(&[(
            "fragment/tree/etc/yum.repos.d/epel.repo",
            b"[epel]\nbaseurl=https://example.com/epel/\n",
            0o755,
        )]);
        let cis_layer = build_fixture_layer(&[
            (
                "fragment/tree/usr/lib/sysctl.d/99-hardening.conf",
                b"kernel.randomize_va_space=2\n",
                0o755,
            ),
            (
                "fragment/hooks/configure.sh",
                b"#!/bin/sh\necho hi\n",
                0o755,
            ),
        ]);

        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        let manifest_path = workdir.path().join("osfragment-assemble.yaml");
        fs::write(&manifest_path, "base: example\n").unwrap();

        let fragments = vec![test_loaded_fragment("epel"), test_loaded_fragment("cis")];
        write_output_with(
            &dir,
            &manifest_path,
            "FROM example\n",
            &fragments,
            |image_ref, dest| {
                let layer: &[u8] = match image_ref {
                    "quay.io/test/epel:1" => &epel_layer,
                    "quay.io/test/cis:1" => &cis_layer,
                    other => panic!("unexpected image_ref in test: {other}"),
                };
                crate::loader::extract_fragment_payload_to_disk(
                    layer,
                    dest,
                    MountMaterialization::Skip,
                )
            },
        )
        .unwrap();

        let archive_path = create_archive(&dir).unwrap();

        let extract_dir = workdir.path().join("extracted");
        fs::create_dir_all(&extract_dir).unwrap();
        let file = fs::File::open(&archive_path).unwrap();
        let decoder = flate2::read::GzDecoder::new(file);
        let mut archive = tar::Archive::new(decoder);
        archive.unpack(&extract_dir).unwrap();
        let extracted_root = extract_dir.join("ctx");

        for rel in [
            "Containerfile",
            "manifest.yaml",
            SENTINEL_FILENAME,
            "fragments/epel/tree/etc/yum.repos.d/epel.repo",
            "fragments/cis/tree/usr/lib/sysctl.d/99-hardening.conf",
            "fragments/cis/hooks/configure.sh",
        ] {
            let original = fs::read(dir.join(rel)).unwrap();
            let extracted = fs::read(extracted_root.join(rel)).unwrap();
            assert_eq!(
                original, extracted,
                "{} did not round-trip byte for byte",
                rel
            );
        }
    }

    #[test]
    fn hooks_only_fragment_materializes_hooks_without_tree_dir() {
        // A fragment with hooks but no tree/ content must produce
        // fragments/<name>/hooks/ and no fragments/<name>/tree/ at all,
        // not an empty tree/ directory.
        let hooks_only_layer =
            build_fixture_layer(&[("fragment/hooks/setup.sh", b"#!/bin/sh\necho setup\n", 0o755)]);

        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        let manifest_path = workdir.path().join("osfragment-assemble.yaml");
        fs::write(&manifest_path, "base: example\n").unwrap();

        let fragments = vec![test_loaded_fragment("hooks-only")];
        write_output_with(
            &dir,
            &manifest_path,
            "FROM example\n",
            &fragments,
            |_image_ref, dest| {
                crate::loader::extract_fragment_payload_to_disk(
                    &hooks_only_layer,
                    dest,
                    MountMaterialization::Skip,
                )
            },
        )
        .unwrap();

        assert!(dir.join("fragments/hooks-only/hooks/setup.sh").exists());
        assert!(
            !dir.join("fragments/hooks-only/tree").exists(),
            "a hooks-only fragment must not produce a tree/ directory"
        );
    }

    /// Builds a `LoadedFragment` whose metadata paths are derived from its
    /// fixture layer entries the same way `load_registry_fragment` derives
    /// them from a real layer: `tree_paths` relative to `fragment/`,
    /// `hook_paths` relative to `fragment/hooks/`. The fixture's tar entries
    /// stay the single source of truth for both the metadata the generator
    /// emits from and the bytes `extract_fragment_payload_to_disk` writes,
    /// which is what keeps the seam test below from confirming itself.
    fn fixture_fragment(
        name: &str,
        manifest_index: usize,
        entries: &[(&str, &[u8], u32)],
    ) -> LoadedFragment {
        let mut loaded = test_loaded_fragment(name);
        loaded.manifest_index = manifest_index;
        loaded.tree_paths = entries
            .iter()
            .filter_map(|(p, _, _)| Path::new(p).strip_prefix("fragment").ok())
            .map(Path::to_path_buf)
            .collect();
        let mut hook_paths: Vec<PathBuf> = entries
            .iter()
            .filter_map(|(p, _, _)| Path::new(p).strip_prefix("fragment/hooks").ok())
            .map(Path::to_path_buf)
            .collect();
        hook_paths.sort();
        loaded.hook_paths = hook_paths;
        loaded
    }

    /// Every build-context path an emitted Containerfile references, taken
    /// from `COPY` sources and bind-mount `source=` options alike. Splitting
    /// on whitespace and commas covers both forms in one pass; a trailing
    /// `/` is trimmed so each result can be checked against the tree
    /// directly.
    fn context_paths_referenced(containerfile: &str) -> Vec<String> {
        let mut refs = Vec::new();
        for token in containerfile.split(|c: char| c.is_whitespace() || c == ',') {
            let token = token.strip_prefix("source=").unwrap_or(token);
            if let Some(rest) = token.strip_prefix("fragments/") {
                refs.push(format!("fragments/{}", rest.trim_end_matches('/')));
            }
        }
        refs
    }

    #[test]
    fn emitted_containerfile_paths_resolve_in_the_materialized_tree() {
        // The seam that was previously verified only by inspection: the
        // generator emits `fragments/<name>/tree|hooks/...` paths from a
        // fragment's metadata, while write_output and
        // extract_fragment_payload_to_disk independently decide where those
        // files actually land. Nothing composed the two. This test generates
        // the Containerfile and materializes the same fixture layers into one
        // tree, then requires every build-context path the Containerfile
        // names to exist on disk and to be carried by the archive.
        //
        // The third fragment is hooks-only: it must contribute the hook mount
        // and no COPY, since it has no tree/ content to copy from.
        let epel_entries: [(&str, &[u8], u32); 2] = [
            (
                "fragment/tree/etc/yum.repos.d/epel.repo",
                b"[epel]\nbaseurl=https://example.com/epel/\n",
                0o644,
            ),
            (
                "fragment/tree/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL",
                b"-----BEGIN PGP PUBLIC KEY BLOCK-----\n",
                0o644,
            ),
        ];
        let cis_entries: [(&str, &[u8], u32); 2] = [
            (
                "fragment/tree/usr/lib/sysctl.d/99-hardening.conf",
                b"kernel.randomize_va_space=2\n",
                0o644,
            ),
            (
                "fragment/hooks/entrypoint",
                b"#!/bin/sh\necho configure\n",
                0o755,
            ),
        ];
        let hooks_only_entries: [(&str, &[u8], u32); 1] = [(
            "fragment/hooks/entrypoint",
            b"#!/bin/sh\necho setup\n",
            0o755,
        )];

        let fragments = vec![
            fixture_fragment("epel", 0, &epel_entries),
            fixture_fragment("cis", 1, &cis_entries),
            fixture_fragment("hooks-only", 2, &hooks_only_entries),
        ];

        let manifest = crate::manifest::Manifest {
            base: "registry.example/base:1".into(),
            source_path: "test-manifest.yaml".into(),
            fragments: vec![
                crate::manifest::ManifestFragment {
                    image: "quay.io/test/epel:1".into(),
                    packages: vec![],
                    mirror: None,
                },
                crate::manifest::ManifestFragment {
                    image: "quay.io/test/cis:1".into(),
                    packages: vec![],
                    mirror: None,
                },
                crate::manifest::ManifestFragment {
                    image: "quay.io/test/hooks-only:1".into(),
                    packages: vec![],
                    mirror: None,
                },
            ],
        };
        let containerfile =
            crate::generator::generate_containerfile(&manifest, &fragments, None, false, true)
                .unwrap();

        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        // Deliberately not named osfragment-assemble.yaml: the copy must land
        // at the fixed name regardless of what the input was called.
        let manifest_path = workdir.path().join("my-composition.yml");
        fs::write(&manifest_path, "base: registry.example/base:1\n").unwrap();

        write_output_with(
            &dir,
            &manifest_path,
            &containerfile,
            &fragments,
            |image_ref, dest| {
                let entries: &[(&str, &[u8], u32)] = match image_ref {
                    "quay.io/test/epel:1" => &epel_entries,
                    "quay.io/test/cis:1" => &cis_entries,
                    "quay.io/test/hooks-only:1" => &hooks_only_entries,
                    other => panic!("unexpected image_ref in test: {other}"),
                };
                crate::loader::extract_fragment_payload_to_disk(
                    &build_fixture_layer(entries),
                    dest,
                    MountMaterialization::Skip,
                )
            },
        )
        .unwrap();

        assert_eq!(
            fs::read_to_string(dir.join("manifest.yaml")).unwrap(),
            "base: registry.example/base:1\n",
            "the input manifest must be copied under the fixed manifest.yaml name"
        );

        let refs = context_paths_referenced(&containerfile);
        assert!(
            refs.len() >= 5,
            "expected the repo, rpm-gpg, payload and both hook references, got {refs:?}"
        );
        for reference in &refs {
            assert!(
                dir.join(reference).exists(),
                "Containerfile references {reference}, which materialization did not produce"
            );
        }

        // A hooks-only fragment has nothing to COPY: referencing a tree/
        // directory that materialization correctly never created would fail
        // the build at COPY time.
        assert!(
            !containerfile.contains("fragments/hooks-only/tree"),
            "a hooks-only fragment must not get a COPY of a tree/ that does not exist"
        );
        assert!(
            refs.contains(&"fragments/hooks-only/hooks".to_string()),
            "a hooks-only fragment must still get its hook mount, got {refs:?}"
        );

        // The hook mount's target is /frag-hooks, so each fragment's
        // invocation must resolve to a real file under that fragment's
        // materialized hooks/ directory.
        let lines: Vec<&str> = containerfile.lines().collect();
        let mut checked_hooks = 0;
        for (idx, line) in lines.iter().enumerate() {
            let Some((_, rest)) = line.split_once("source=fragments/") else {
                continue;
            };
            let frag_name = rest
                .split('/')
                .next()
                .expect("split always yields one part");
            let command_line = lines
                .get(idx + 1)
                .expect("a hook mount line is always followed by its command line");
            for token in command_line.split_whitespace() {
                if let Some(hook) = token.strip_prefix("/frag-hooks/") {
                    let on_disk = dir
                        .join("fragments")
                        .join(frag_name)
                        .join("hooks")
                        .join(hook);
                    assert!(
                        on_disk.exists(),
                        "hook command /frag-hooks/{hook} resolves to {}, which does not exist",
                        on_disk.display()
                    );
                    checked_hooks += 1;
                }
            }
        }
        assert_eq!(
            checked_hooks, 2,
            "both hook-bearing fragments' commands must have been checked"
        );

        // The archive is the handoff artifact, so it has to carry every
        // context path the Containerfile needs, not just the tree does.
        let archive_path = create_archive(&dir).unwrap();
        let file = fs::File::open(&archive_path).unwrap();
        let decoder = flate2::read::GzDecoder::new(file);
        let mut archive = tar::Archive::new(decoder);
        let archived: Vec<String> = archive
            .entries()
            .unwrap()
            .map(|e| {
                let path = e.unwrap().path().unwrap().to_path_buf();
                path.strip_prefix("ctx")
                    .unwrap_or(&path)
                    .to_string_lossy()
                    .trim_end_matches('/')
                    .to_string()
            })
            .collect();
        for reference in &refs {
            assert!(
                archived
                    .iter()
                    .any(|e| e == reference || e.starts_with(&format!("{reference}/"))),
                "archive is missing {reference}, which the Containerfile references"
            );
        }
    }

    #[test]
    #[cfg(unix)]
    fn hook_exec_bit_survives_materialization_and_archive() {
        // Carried forward from Task 5 (unexpressible before Task 4's fix
        // round added a mode-aware tarball builder): a hook file's
        // executable bit must survive both extract_fragment_payload_to_disk
        // and the tar round-trip through create_archive, not just its byte
        // content, since hooks are executed directly from the extracted
        // archive. Bidirectional per review Minor 3: also pins a non-
        // executable tree file at 0o644 so a blanket mode promotion (e.g.
        // everything landing at 0o755) would be caught too, not just a
        // dropped exec bit.
        use std::os::unix::fs::PermissionsExt;

        let layer = build_fixture_layer(&[
            ("fragment/hooks/setup.sh", b"#!/bin/sh\necho setup\n", 0o755),
            ("fragment/tree/etc/app.conf", b"key=value\n", 0o644),
        ]);

        let workdir = tempfile::tempdir().unwrap();
        let dest = workdir.path().join("frag");
        crate::loader::extract_fragment_payload_to_disk(&layer, &dest, MountMaterialization::Skip)
            .unwrap();

        let hook_path = dest.join("hooks/setup.sh");
        let hook_mode = fs::metadata(&hook_path).unwrap().permissions().mode() & 0o777;
        assert_eq!(
            hook_mode, 0o755,
            "hook exec bit lost during materialization"
        );

        let conf_path = dest.join("tree/etc/app.conf");
        let conf_mode = fs::metadata(&conf_path).unwrap().permissions().mode() & 0o777;
        assert_eq!(
            conf_mode, 0o644,
            "non-executable tree file must not be promoted to executable during materialization"
        );

        let archive_path = create_archive(&dest).unwrap();
        let extract_dir = workdir.path().join("extracted");
        fs::create_dir_all(&extract_dir).unwrap();
        let file = fs::File::open(&archive_path).unwrap();
        let decoder = flate2::read::GzDecoder::new(file);
        let mut archive = tar::Archive::new(decoder);
        archive.unpack(&extract_dir).unwrap();

        let extracted_hook = extract_dir.join("frag/hooks/setup.sh");
        let hook_mode_in_archive =
            fs::metadata(&extracted_hook).unwrap().permissions().mode() & 0o777;
        assert_eq!(
            hook_mode_in_archive, 0o755,
            "hook exec bit lost through the create_archive round trip"
        );

        let extracted_conf = extract_dir.join("frag/tree/etc/app.conf");
        let conf_mode_in_archive =
            fs::metadata(&extracted_conf).unwrap().permissions().mode() & 0o777;
        assert_eq!(
            conf_mode_in_archive, 0o644,
            "non-executable tree file must not be promoted to executable through create_archive"
        );
    }

    #[test]
    fn archive_path_appends_suffix_without_touching_dots() {
        assert_eq!(
            archive_path_for(Path::new("build/context")),
            PathBuf::from("build/context.tar.gz")
        );
        assert_eq!(
            archive_path_for(Path::new("out.v2")),
            PathBuf::from("out.v2.tar.gz")
        );
    }

    #[test]
    fn archive_path_normalizes_trailing_separator() {
        // Regression test: --self-contained out/ (what shell completion
        // produces for an existing directory) must still yield the
        // sibling out.tar.gz, not a hidden .tar.gz file inside out/ that
        // the next run's check_target_dir_safe would then refuse as
        // foreign.
        assert_eq!(
            archive_path_for(Path::new("out/")),
            PathBuf::from("out.tar.gz")
        );
        assert_eq!(
            archive_path_for(Path::new("build/context/")),
            PathBuf::from("build/context.tar.gz")
        );
    }

    #[test]
    fn archive_contents_match_tree_byte_for_byte() {
        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("myctx");
        fs::create_dir_all(dir.join("fragments/epel/tree/etc/yum.repos.d")).unwrap();
        fs::create_dir_all(dir.join("fragments/cis/hooks")).unwrap();
        fs::write(dir.join("Containerfile"), "FROM registry.example/base:1\n").unwrap();
        fs::write(
            dir.join("manifest.yaml"),
            "apiVersion: osfragment/v1alpha1\n",
        )
        .unwrap();
        fs::write(dir.join(SENTINEL_FILENAME), sentinel_contents()).unwrap();
        fs::write(
            dir.join("fragments/epel/tree/etc/yum.repos.d/epel.repo"),
            "[epel]\nbaseurl=https://example.com/epel/\n",
        )
        .unwrap();
        fs::write(
            dir.join("fragments/cis/hooks/configure.sh"),
            "#!/bin/sh\necho hi\n",
        )
        .unwrap();

        let archive_path = create_archive(&dir).unwrap();
        assert_eq!(
            archive_path,
            PathBuf::from(format!("{}.tar.gz", dir.display()))
        );

        let extract_dir = workdir.path().join("extracted");
        fs::create_dir_all(&extract_dir).unwrap();
        let file = fs::File::open(&archive_path).unwrap();
        let decoder = flate2::read::GzDecoder::new(file);
        let mut archive = tar::Archive::new(decoder);
        archive.unpack(&extract_dir).unwrap();

        let extracted_root = extract_dir.join("myctx");
        for rel in [
            "Containerfile",
            "manifest.yaml",
            SENTINEL_FILENAME,
            "fragments/epel/tree/etc/yum.repos.d/epel.repo",
            "fragments/cis/hooks/configure.sh",
        ] {
            let original = fs::read(dir.join(rel)).unwrap();
            let extracted = fs::read(extracted_root.join(rel)).unwrap();
            assert_eq!(
                original, extracted,
                "{} did not round-trip byte for byte",
                rel
            );
        }
    }

    #[test]
    fn create_archive_leaves_previous_archive_intact_on_failure() {
        // Review Critical 1: create_archive must stage-then-rename like
        // write_output_with, not truncate the destination up front. `dir`
        // is never created, so append_dir_all fails partway through and
        // the pre-existing archive must survive byte for byte.
        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        let archive_path = archive_path_for(&dir);
        let previous_contents = b"a previous good archive, must survive";
        fs::write(&archive_path, previous_contents).unwrap();

        let result = create_archive(&dir);
        assert!(
            result.is_err(),
            "archiving a nonexistent directory must fail"
        );

        let after = fs::read(&archive_path).unwrap();
        assert_eq!(
            after, previous_contents,
            "a failed create_archive must not touch a pre-existing archive"
        );
    }

    #[test]
    #[cfg(unix)]
    fn create_archive_replaces_a_symlinked_archive_path_rather_than_writing_through_it() {
        // Review Critical 1, consequence (b): a pre-existing symlink at
        // <dir>.tar.gz must be replaced by the rename, not written through
        // to whatever it points at.
        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("Containerfile"), "FROM example\n").unwrap();

        let archive_path = archive_path_for(&dir);
        let decoy = workdir.path().join("decoy-target");
        fs::write(&decoy, b"decoy contents, must not be overwritten").unwrap();
        std::os::unix::fs::symlink(&decoy, &archive_path).unwrap();

        let result_path = create_archive(&dir).unwrap();
        assert_eq!(result_path, archive_path);

        let decoy_contents = fs::read(&decoy).unwrap();
        assert_eq!(
            decoy_contents, b"decoy contents, must not be overwritten",
            "the symlink's target must not be written through"
        );

        let archive_meta = fs::symlink_metadata(&archive_path).unwrap();
        assert!(
            !archive_meta.file_type().is_symlink(),
            "the symlinked archive path must be replaced with a regular file, not written through"
        );
    }

    #[test]
    fn write_output_stages_then_swaps_atomically() {
        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        let manifest_path = workdir.path().join("osfragment-assemble.yaml");
        fs::write(&manifest_path, "base: example\n").unwrap();

        let fragments = vec![test_loaded_fragment("epel"), test_loaded_fragment("cis")];
        write_output_with(
            &dir,
            &manifest_path,
            "FROM example\n",
            &fragments,
            |_r, d| fs::create_dir_all(d).map_err(Into::into),
        )
        .unwrap();

        assert_eq!(
            fs::read_to_string(dir.join("Containerfile")).unwrap(),
            "FROM example\n"
        );
        assert_eq!(
            fs::read_to_string(dir.join("manifest.yaml")).unwrap(),
            "base: example\n"
        );
        assert!(dir.join("fragments/epel").is_dir());
        assert!(dir.join("fragments/cis").is_dir());
        assert!(
            dir.join(SENTINEL_FILENAME).exists(),
            "sentinel must be written into the output tree"
        );
    }

    #[test]
    fn write_output_replaces_prior_tool_generated_directory() {
        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        fs::create_dir_all(dir.join("fragments/old-frag")).unwrap();
        fs::write(dir.join("Containerfile"), "OLD CONTENT\n").unwrap();
        fs::write(dir.join(SENTINEL_FILENAME), sentinel_contents()).unwrap();

        let manifest_path = workdir.path().join("osfragment-assemble.yaml");
        fs::write(&manifest_path, "base: example\n").unwrap();

        let fragments: Vec<LoadedFragment> = vec![];
        write_output_with(
            &dir,
            &manifest_path,
            "NEW CONTENT\n",
            &fragments,
            |_r, d| fs::create_dir_all(d).map_err(Into::into),
        )
        .unwrap();

        assert_eq!(
            fs::read_to_string(dir.join("Containerfile")).unwrap(),
            "NEW CONTENT\n"
        );
        assert!(!dir.join("fragments/old-frag").exists());
        assert!(dir.join(SENTINEL_FILENAME).exists());
    }

    #[test]
    fn regeneration_is_idempotent_and_passes_safety_check_again() {
        // The update model's central operation: run write_output_with twice
        // against the same target with the same inputs. The second run must
        // pass check_target_dir_safe against the first run's own output (the
        // whole point of the sentinel) and must produce byte-identical
        // content, since output is a pure function of manifest and registry
        // state.
        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        let manifest_path = workdir.path().join("osfragment-assemble.yaml");
        fs::write(&manifest_path, "base: example\n").unwrap();
        let fragments = vec![test_loaded_fragment("epel")];

        for _ in 0..2 {
            write_output_with(
                &dir,
                &manifest_path,
                "FROM example\n",
                &fragments,
                |_r, d| fs::create_dir_all(d).map_err(Into::into),
            )
            .unwrap();
        }

        assert_eq!(
            fs::read_to_string(dir.join("Containerfile")).unwrap(),
            "FROM example\n"
        );
        assert_eq!(
            fs::read_to_string(dir.join("manifest.yaml")).unwrap(),
            "base: example\n"
        );
        assert!(dir.join("fragments/epel").is_dir());
        assert!(dir.join(SENTINEL_FILENAME).exists());
    }

    #[test]
    fn write_output_refuses_unsafe_target_dir() {
        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("README.md"), "mine").unwrap();

        let manifest_path = workdir.path().join("osfragment-assemble.yaml");
        fs::write(&manifest_path, "base: example\n").unwrap();

        let fragments: Vec<LoadedFragment> = vec![];
        let result = write_output_with(&dir, &manifest_path, "X\n", &fragments, |_r, d| {
            fs::create_dir_all(d).map_err(Into::into)
        });

        assert!(result.is_err());
        assert!(
            dir.join("README.md").exists(),
            "unrelated file must survive a refused run"
        );
    }

    #[test]
    fn write_output_leaves_no_partial_tree_on_materialization_failure() {
        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        fs::create_dir_all(dir.join("fragments/prior-run")).unwrap();
        fs::write(dir.join("Containerfile"), "PRIOR RUN\n").unwrap();
        fs::write(dir.join(SENTINEL_FILENAME), sentinel_contents()).unwrap();

        let manifest_path = workdir.path().join("osfragment-assemble.yaml");
        fs::write(&manifest_path, "base: example\n").unwrap();

        let fragments = vec![
            test_loaded_fragment("good-frag"),
            test_loaded_fragment("bad-frag"),
        ];
        let result = write_output_with(
            &dir,
            &manifest_path,
            "NEW\n",
            &fragments,
            |image_ref, dest| {
                if image_ref.contains("bad-frag") {
                    bail!("simulated registry failure");
                }
                fs::create_dir_all(dest).map_err(Into::into)
            },
        );

        assert!(result.is_err());
        assert_eq!(
            fs::read_to_string(dir.join("Containerfile")).unwrap(),
            "PRIOR RUN\n"
        );
        assert!(dir.join("fragments/prior-run").exists());
        assert!(
            dir.join(SENTINEL_FILENAME).exists(),
            "the prior run's sentinel must survive a failed regeneration untouched"
        );
        assert!(!dir.join("fragments/good-frag").exists());

        // The staging directory is a sibling of <dir> because that is what
        // makes the swap rename atomic (see the comment at its creation
        // site); incidentally, that also means a leaked one would litter the
        // user's working directory rather than $TMPDIR. TempDir's Drop must
        // reclaim it
        // on every failure up to and including the removal of an existing
        // <dir>, which covers a materialization failure like this one. Past
        // the removal keep() has deliberately disarmed the cleanup, so a
        // failing rename is the one case that does leave the staging tree
        // behind, with the complete output in it.
        let leaked: Vec<_> = fs::read_dir(workdir.path())
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().to_string())
            .filter(|n| n.starts_with(".osfragment-assemble-staging-"))
            .collect();
        assert!(
            leaked.is_empty(),
            "staging directory leaked on the error path: {leaked:?}"
        );
    }

    #[test]
    fn write_output_refuses_when_target_gains_a_foreign_file_during_materialization() {
        // The safety checks run before minutes of registry I/O. Anything that
        // lands in <dir> while the pulls are in flight is a file the checks
        // never saw, so the re-check immediately before the destructive step
        // must refuse rather than delete it.
        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        fs::create_dir_all(&dir).unwrap();

        let manifest_path = workdir.path().join("osfragment-assemble.yaml");
        fs::write(&manifest_path, "base: example\n").unwrap();

        let fragments = vec![test_loaded_fragment("epel")];
        let result = write_output_with(&dir, &manifest_path, "NEW\n", &fragments, |_r, d| {
            // Stands in for a concurrent writer during the pull window.
            fs::write(dir.join("README.md"), "appeared mid-run").unwrap();
            fs::create_dir_all(d).map_err(Into::into)
        });

        assert!(result.is_err());
        assert!(
            dir.join("README.md").exists(),
            "a file that appeared during materialization must not be deleted"
        );
    }

    #[test]
    fn write_output_writes_only_the_tool_generated_entry_set() {
        // Anything the tool writes at the top level of <dir> outside the
        // four recognized names would make check_target_dir_safe refuse the
        // tool's own output on the next regeneration.
        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        let manifest_path = workdir.path().join("osfragment-assemble.yaml");
        fs::write(&manifest_path, "base: example\n").unwrap();

        let fragments = vec![test_loaded_fragment("epel")];
        write_output_with(
            &dir,
            &manifest_path,
            "FROM example\n",
            &fragments,
            |_r, d| fs::create_dir_all(d).map_err(Into::into),
        )
        .unwrap();

        let mut entries: Vec<_> = fs::read_dir(&dir)
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().to_string())
            .collect();
        entries.sort();
        let mut expected: Vec<_> = TOOL_GENERATED_ENTRIES
            .iter()
            .map(|e| e.to_string())
            .collect();
        expected.sort();
        assert_eq!(entries, expected);
    }

    #[test]
    #[cfg(unix)]
    fn write_output_refuses_symlinked_target() {
        // `exists()` and `is_dir()` both resolve through a symlink, so a
        // symlinked target would otherwise pass the safety check against
        // the link's target and then have the tool remove and replace
        // whatever the link points at, outside the path the user named.
        let workdir = tempfile::tempdir().unwrap();
        let real = workdir.path().join("somewhere-else");
        fs::create_dir_all(real.join("fragments")).unwrap();
        fs::write(real.join("Containerfile"), "REAL\n").unwrap();
        fs::write(real.join(SENTINEL_FILENAME), sentinel_contents()).unwrap();

        let dir = workdir.path().join("ctx");
        std::os::unix::fs::symlink(&real, &dir).unwrap();

        let manifest_path = workdir.path().join("osfragment-assemble.yaml");
        fs::write(&manifest_path, "base: example\n").unwrap();

        let fragments: Vec<LoadedFragment> = vec![];
        let err = write_output_with(&dir, &manifest_path, "NEW\n", &fragments, |_r, d| {
            fs::create_dir_all(d).map_err(Into::into)
        })
        .unwrap_err();

        assert!(
            err.to_string().contains("is a symlink"),
            "error must name the symlink case, got: {err}"
        );
        assert_eq!(
            fs::read_to_string(real.join("Containerfile")).unwrap(),
            "REAL\n",
            "the symlink's target must not be touched"
        );
    }

    #[test]
    #[cfg(unix)]
    fn write_output_refuses_dangling_symlink_target() {
        // A dangling symlink reads as absent through `exists()`, so without
        // an explicit check the run would proceed all the way to the final
        // rename and fail there with a confusing ENOTDIR instead.
        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        std::os::unix::fs::symlink(workdir.path().join("no-such-target"), &dir).unwrap();

        let manifest_path = workdir.path().join("osfragment-assemble.yaml");
        fs::write(&manifest_path, "base: example\n").unwrap();

        let fragments: Vec<LoadedFragment> = vec![];
        let err = write_output_with(&dir, &manifest_path, "NEW\n", &fragments, |_r, d| {
            fs::create_dir_all(d).map_err(Into::into)
        })
        .unwrap_err();

        assert!(
            err.to_string().contains("is a symlink"),
            "error must name the symlink case, got: {err}"
        );
    }

    /// Every fragment directory this function creates must be a direct child
    /// of `fragments/`. That holds because `fragment.name` is a
    /// `FragmentName`, whose grammar admits no separator and no `..`, so the
    /// join below cannot leave the staged tree. Before that type existed, a
    /// fragment named `../../escape` materialized into a sibling of the
    /// output directory entirely.
    ///
    /// The escape is now unrepresentable rather than merely unreached, so
    /// this test states the property the type is carrying; the rejection
    /// itself is pinned in `src/fragment.rs`.
    #[test]
    fn materialized_fragment_dirs_stay_inside_the_output_tree() {
        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        let manifest_path = workdir.path().join("osfragment-assemble.yaml");
        fs::write(&manifest_path, "base: example\n").unwrap();

        let fragments = vec![test_loaded_fragment("epel"), test_loaded_fragment("cis")];
        let staged_dests = std::cell::RefCell::new(Vec::new());
        write_output_with(
            &dir,
            &manifest_path,
            "FROM example\n",
            &fragments,
            |_r, d| {
                staged_dests.borrow_mut().push(d.to_path_buf());
                fs::create_dir_all(d).map_err(Into::into)
            },
        )
        .unwrap();

        for dest in staged_dests.borrow().iter() {
            assert_eq!(
                dest.parent().and_then(Path::file_name),
                Some(std::ffi::OsStr::new("fragments")),
                "{} is not a direct child of fragments/",
                dest.display()
            );
            assert!(
                !dest.to_string_lossy().contains(".."),
                "{} contains a traversal component",
                dest.display()
            );
        }
    }

    #[test]
    fn write_output_normalizes_directory_permissions() {
        // Regression test: the staging tempdir is created at 0700; without
        // an explicit fix that mode survives the rename into <dir> and
        // then into every tar header create_archive writes, which is wrong
        // for a handoff artifact meant to be committed and shared.
        let workdir = tempfile::tempdir().unwrap();
        let dir = workdir.path().join("ctx");
        let manifest_path = workdir.path().join("osfragment-assemble.yaml");
        fs::write(&manifest_path, "base: example\n").unwrap();

        let fragments: Vec<LoadedFragment> = vec![];
        write_output_with(
            &dir,
            &manifest_path,
            "FROM example\n",
            &fragments,
            |_r, d| fs::create_dir_all(d).map_err(Into::into),
        )
        .unwrap();

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = fs::metadata(&dir).unwrap().permissions().mode() & 0o777;
            assert_eq!(
                mode, OUTPUT_DIR_MODE,
                "output directory must not carry the staging tempdir's 0700"
            );
        }
    }
}
